// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	wave "WaveSight/internal/domain/wave"
	market "WaveSight/internal/market"
	repository "WaveSight/pkg/repository"
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeWaveSightPkgApi(in *jlexer.Lexer, out *SnapshotHistory) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]repository.SnapshotMetadata, 0, 0)
					} else {
						out.Items = []repository.SnapshotMetadata{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v1 repository.SnapshotMetadata
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightPkgApi(out *jwriter.Writer, in SnapshotHistory) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix[1:])
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Items {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SnapshotHistory) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightPkgApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SnapshotHistory) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightPkgApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SnapshotHistory) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightPkgApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SnapshotHistory) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightPkgApi(l, v)
}
func easyjson6601e8cdDecodeWaveSightPkgApi1(in *jlexer.Lexer, out *Problem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = int(in.Int())
			}
		case "detail":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Detail = string(in.String())
			}
		case "request_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RequestID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightPkgApi1(out *jwriter.Writer, in Problem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.Int(int(in.Status))
	}
	{
		const prefix string = ",\"detail\":"
		out.RawString(prefix)
		out.String(string(in.Detail))
	}
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix)
		out.String(string(in.RequestID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Problem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightPkgApi1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Problem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightPkgApi1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Problem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightPkgApi1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Problem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightPkgApi1(l, v)
}
func easyjson6601e8cdDecodeWaveSightPkgApi2(in *jlexer.Lexer, out *AnalysisSnapshot) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "theory_version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TheoryVersion = string(in.String())
			}
		case "engine_version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EngineVersion = string(in.String())
			}
		case "generated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GeneratedAt = int64(in.Int64())
			}
		case "request":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Request).UnmarshalEasyJSON(in)
			}
		case "data_quality":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.DataQuality).UnmarshalEasyJSON(in)
			}
		case "candles":
			if in.IsNull() {
				in.Skip()
				out.Candles = nil
			} else {
				in.Delim('[')
				if out.Candles == nil {
					if !in.IsDelim(']') {
						out.Candles = make([]market.Candle, 0, 1)
					} else {
						out.Candles = []market.Candle{}
					}
				} else {
					out.Candles = (out.Candles)[:0]
				}
				for !in.IsDelim(']') {
					var v4 market.Candle
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Candles = append(out.Candles, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "scenarios":
			if in.IsNull() {
				in.Skip()
				out.Scenarios = nil
			} else {
				in.Delim('[')
				if out.Scenarios == nil {
					if !in.IsDelim(']') {
						out.Scenarios = make([]wave.Scenario, 0, 0)
					} else {
						out.Scenarios = []wave.Scenario{}
					}
				} else {
					out.Scenarios = (out.Scenarios)[:0]
				}
				for !in.IsDelim(']') {
					var v5 wave.Scenario
					if in.IsNull() {
						in.Skip()
					} else {
						(v5).UnmarshalEasyJSON(in)
					}
					out.Scenarios = append(out.Scenarios, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "future_bars":
			if in.IsNull() {
				in.Skip()
				out.FutureBars = nil
			} else {
				in.Delim('[')
				if out.FutureBars == nil {
					if !in.IsDelim(']') {
						out.FutureBars = make([]int64, 0, 8)
					} else {
						out.FutureBars = []int64{}
					}
				} else {
					out.FutureBars = (out.FutureBars)[:0]
				}
				for !in.IsDelim(']') {
					var v6 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v6 = int64(in.Int64())
					}
					out.FutureBars = append(out.FutureBars, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightPkgApi2(out *jwriter.Writer, in AnalysisSnapshot) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"theory_version\":"
		out.RawString(prefix)
		out.String(string(in.TheoryVersion))
	}
	{
		const prefix string = ",\"engine_version\":"
		out.RawString(prefix)
		out.String(string(in.EngineVersion))
	}
	{
		const prefix string = ",\"generated_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.GeneratedAt))
	}
	{
		const prefix string = ",\"request\":"
		out.RawString(prefix)
		(in.Request).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"data_quality\":"
		out.RawString(prefix)
		(in.DataQuality).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"candles\":"
		out.RawString(prefix)
		if in.Candles == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.Candles {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"scenarios\":"
		out.RawString(prefix)
		if in.Scenarios == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Scenarios {
				if v9 > 0 {
					out.RawByte(',')
				}
				(v10).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"future_bars\":"
		out.RawString(prefix)
		if in.FutureBars == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.FutureBars {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v12))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalysisSnapshot) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightPkgApi2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalysisSnapshot) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightPkgApi2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalysisSnapshot) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightPkgApi2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalysisSnapshot) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightPkgApi2(l, v)
}
func easyjson6601e8cdDecodeWaveSightPkgApi3(in *jlexer.Lexer, out *AnalysisRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "timeframe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timeframe = string(in.String())
			}
		case "session":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Session = string(in.String())
			}
		case "as_of":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AsOf = string(in.String())
			}
		case "lookback_bars":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LookbackBars = int(in.Int())
			}
		case "max_scenarios":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxScenarios = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightPkgApi3(out *jwriter.Writer, in AnalysisRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"timeframe\":"
		out.RawString(prefix)
		out.String(string(in.Timeframe))
	}
	{
		const prefix string = ",\"session\":"
		out.RawString(prefix)
		out.String(string(in.Session))
	}
	if in.AsOf != "" {
		const prefix string = ",\"as_of\":"
		out.RawString(prefix)
		out.String(string(in.AsOf))
	}
	if in.LookbackBars != 0 {
		const prefix string = ",\"lookback_bars\":"
		out.RawString(prefix)
		out.Int(int(in.LookbackBars))
	}
	if in.MaxScenarios != 0 {
		const prefix string = ",\"max_scenarios\":"
		out.RawString(prefix)
		out.Int(int(in.MaxScenarios))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalysisRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightPkgApi3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalysisRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightPkgApi3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalysisRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightPkgApi3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalysisRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightPkgApi3(l, v)
}
