// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package market

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3b07ea0fDecodeWaveSightInternalMarket(in *jlexer.Lexer, out *DerivedCandle) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "high_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HighTime = int64(in.Int64())
			}
		case "low_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LowTime = int64(in.Int64())
			}
		case "source_from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceFrom = int64(in.Int64())
			}
		case "source_to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceTo = int64(in.Int64())
			}
		case "provenance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Provenance = BarProvenance(in.String())
			}
		case "partial":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Partial = bool(in.Bool())
			}
		case "time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "bar_index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BarIndex = int(in.Int())
			}
		case "open":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Open = float64(in.Float64())
			}
		case "high":
			if in.IsNull() {
				in.Skip()
			} else {
				out.High = float64(in.Float64())
			}
		case "low":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Low = float64(in.Float64())
			}
		case "close":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Close = float64(in.Float64())
			}
		case "volume":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Volume = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b07ea0fEncodeWaveSightInternalMarket(out *jwriter.Writer, in DerivedCandle) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"high_time\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.HighTime))
	}
	{
		const prefix string = ",\"low_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.LowTime))
	}
	{
		const prefix string = ",\"source_from\":"
		out.RawString(prefix)
		out.Int64(int64(in.SourceFrom))
	}
	{
		const prefix string = ",\"source_to\":"
		out.RawString(prefix)
		out.Int64(int64(in.SourceTo))
	}
	{
		const prefix string = ",\"provenance\":"
		out.RawString(prefix)
		out.String(string(in.Provenance))
	}
	{
		const prefix string = ",\"partial\":"
		out.RawString(prefix)
		out.Bool(bool(in.Partial))
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"bar_index\":"
		out.RawString(prefix)
		out.Int(int(in.BarIndex))
	}
	{
		const prefix string = ",\"open\":"
		out.RawString(prefix)
		out.Float64(float64(in.Open))
	}
	{
		const prefix string = ",\"high\":"
		out.RawString(prefix)
		out.Float64(float64(in.High))
	}
	{
		const prefix string = ",\"low\":"
		out.RawString(prefix)
		out.Float64(float64(in.Low))
	}
	{
		const prefix string = ",\"close\":"
		out.RawString(prefix)
		out.Float64(float64(in.Close))
	}
	{
		const prefix string = ",\"volume\":"
		out.RawString(prefix)
		out.Float64(float64(in.Volume))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DerivedCandle) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b07ea0fEncodeWaveSightInternalMarket(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DerivedCandle) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b07ea0fEncodeWaveSightInternalMarket(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DerivedCandle) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b07ea0fDecodeWaveSightInternalMarket(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DerivedCandle) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b07ea0fDecodeWaveSightInternalMarket(l, v)
}
func easyjson3b07ea0fDecodeWaveSightInternalMarket1(in *jlexer.Lexer, out *CanonicalViews) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Views":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Views = make(map[Timeframe][]DerivedCandle)
				for !in.IsDelim('}') {
					key := Timeframe(in.String())
					in.WantColon()
					var v1 []DerivedCandle
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						in.Delim('[')
						if v1 == nil {
							if !in.IsDelim(']') {
								v1 = make([]DerivedCandle, 0, 0)
							} else {
								v1 = []DerivedCandle{}
							}
						} else {
							v1 = (v1)[:0]
						}
						for !in.IsDelim(']') {
							var v2 DerivedCandle
							if in.IsNull() {
								in.Skip()
							} else {
								(v2).UnmarshalEasyJSON(in)
							}
							v1 = append(v1, v2)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.Views)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "NativeDaily":
			if in.IsNull() {
				in.Skip()
				out.NativeDaily = nil
			} else {
				in.Delim('[')
				if out.NativeDaily == nil {
					if !in.IsDelim(']') {
						out.NativeDaily = make([]DerivedCandle, 0, 0)
					} else {
						out.NativeDaily = []DerivedCandle{}
					}
				} else {
					out.NativeDaily = (out.NativeDaily)[:0]
				}
				for !in.IsDelim(']') {
					var v3 DerivedCandle
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.NativeDaily = append(out.NativeDaily, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b07ea0fEncodeWaveSightInternalMarket1(out *jwriter.Writer, in CanonicalViews) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Views\":"
		out.RawString(prefix[1:])
		if in.Views == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.Views {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				if v4Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v5, v6 := range v4Value {
						if v5 > 0 {
							out.RawByte(',')
						}
						(v6).MarshalEasyJSON(out)
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"NativeDaily\":"
		out.RawString(prefix)
		if in.NativeDaily == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.NativeDaily {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CanonicalViews) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b07ea0fEncodeWaveSightInternalMarket1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CanonicalViews) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b07ea0fEncodeWaveSightInternalMarket1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CanonicalViews) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b07ea0fDecodeWaveSightInternalMarket1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CanonicalViews) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b07ea0fDecodeWaveSightInternalMarket1(l, v)
}
