// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package wave

import (
	market "WaveSight/internal/market"
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeWaveSightInternalDomainWave(in *jlexer.Lexer, out *WaveNode) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "pattern":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Pattern = PatternType(in.String())
			}
		case "mode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Mode = WaveMode(in.String())
			}
		case "function":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Function = WaveFunction(in.String())
			}
		case "direction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Direction = Direction(in.String())
			}
		case "degree":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Degree = Degree(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = WaveStatus(in.String())
			}
		case "label":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Label = string(in.String())
			}
		case "level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Level = int(in.Int())
			}
		case "orthodox_start":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.OrthodoxStart).UnmarshalEasyJSON(in)
			}
		case "orthodox_end":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.OrthodoxEnd).UnmarshalEasyJSON(in)
			}
		case "pivots":
			if in.IsNull() {
				in.Skip()
				out.Pivots = nil
			} else {
				in.Delim('[')
				if out.Pivots == nil {
					if !in.IsDelim(']') {
						out.Pivots = make([]Pivot, 0, 1)
					} else {
						out.Pivots = []Pivot{}
					}
				} else {
					out.Pivots = (out.Pivots)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Pivot
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Pivots = append(out.Pivots, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "children":
			if in.IsNull() {
				in.Skip()
				out.Children = nil
			} else {
				in.Delim('[')
				if out.Children == nil {
					if !in.IsDelim(']') {
						out.Children = make([]WaveNode, 0, 0)
					} else {
						out.Children = []WaveNode{}
					}
				} else {
					out.Children = (out.Children)[:0]
				}
				for !in.IsDelim(']') {
					var v2 WaveNode
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.Children = append(out.Children, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "measurements":
			if in.IsNull() {
				in.Skip()
				out.Measurements = nil
			} else {
				in.Delim('[')
				if out.Measurements == nil {
					if !in.IsDelim(']') {
						out.Measurements = make([]Measurement, 0, 1)
					} else {
						out.Measurements = []Measurement{}
					}
				} else {
					out.Measurements = (out.Measurements)[:0]
				}
				for !in.IsDelim(']') {
					var v3 Measurement
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.Measurements = append(out.Measurements, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "rule_evaluations":
			if in.IsNull() {
				in.Skip()
				out.RuleEvaluations = nil
			} else {
				in.Delim('[')
				if out.RuleEvaluations == nil {
					if !in.IsDelim(']') {
						out.RuleEvaluations = make([]RuleEvaluation, 0, 0)
					} else {
						out.RuleEvaluations = []RuleEvaluation{}
					}
				} else {
					out.RuleEvaluations = (out.RuleEvaluations)[:0]
				}
				for !in.IsDelim(']') {
					var v4 RuleEvaluation
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.RuleEvaluations = append(out.RuleEvaluations, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "conformance":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Conformance).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave(out *jwriter.Writer, in WaveNode) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"pattern\":"
		out.RawString(prefix)
		out.String(string(in.Pattern))
	}
	{
		const prefix string = ",\"mode\":"
		out.RawString(prefix)
		out.String(string(in.Mode))
	}
	{
		const prefix string = ",\"function\":"
		out.RawString(prefix)
		out.String(string(in.Function))
	}
	{
		const prefix string = ",\"direction\":"
		out.RawString(prefix)
		out.String(string(in.Direction))
	}
	{
		const prefix string = ",\"degree\":"
		out.RawString(prefix)
		out.String(string(in.Degree))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"label\":"
		out.RawString(prefix)
		out.String(string(in.Label))
	}
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix)
		out.Int(int(in.Level))
	}
	{
		const prefix string = ",\"orthodox_start\":"
		out.RawString(prefix)
		(in.OrthodoxStart).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"orthodox_end\":"
		out.RawString(prefix)
		(in.OrthodoxEnd).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"pivots\":"
		out.RawString(prefix)
		if in.Pivots == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Pivots {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Children) != 0 {
		const prefix string = ",\"children\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v7, v8 := range in.Children {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Measurements) != 0 {
		const prefix string = ",\"measurements\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v9, v10 := range in.Measurements {
				if v9 > 0 {
					out.RawByte(',')
				}
				(v10).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"rule_evaluations\":"
		out.RawString(prefix)
		if in.RuleEvaluations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.RuleEvaluations {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"conformance\":"
		out.RawString(prefix)
		(in.Conformance).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WaveNode) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WaveNode) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WaveNode) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WaveNode) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave1(in *jlexer.Lexer, out *TimeWindow) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start_bar_offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartBarOffset = int(in.Int())
			}
		case "end_bar_offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndBarOffset = int(in.Int())
			}
		case "start_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartTime = int64(in.Int64())
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndTime = int64(in.Int64())
			}
		case "evidence":
			if in.IsNull() {
				in.Skip()
				out.Evidence = nil
			} else {
				in.Delim('[')
				if out.Evidence == nil {
					if !in.IsDelim(']') {
						out.Evidence = make([]string, 0, 4)
					} else {
						out.Evidence = []string{}
					}
				} else {
					out.Evidence = (out.Evidence)[:0]
				}
				for !in.IsDelim(']') {
					var v13 string
					if in.IsNull() {
						in.Skip()
					} else {
						v13 = string(in.String())
					}
					out.Evidence = append(out.Evidence, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave1(out *jwriter.Writer, in TimeWindow) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start_bar_offset\":"
		out.RawString(prefix[1:])
		out.Int(int(in.StartBarOffset))
	}
	{
		const prefix string = ",\"end_bar_offset\":"
		out.RawString(prefix)
		out.Int(int(in.EndBarOffset))
	}
	if in.StartTime != 0 {
		const prefix string = ",\"start_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.StartTime))
	}
	if in.EndTime != 0 {
		const prefix string = ",\"end_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.EndTime))
	}
	{
		const prefix string = ",\"evidence\":"
		out.RawString(prefix)
		if in.Evidence == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Evidence {
				if v14 > 0 {
					out.RawByte(',')
				}
				out.String(string(v15))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TimeWindow) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TimeWindow) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TimeWindow) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TimeWindow) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave1(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave2(in *jlexer.Lexer, out *TargetZone) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "wave_label":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WaveLabel = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = TargetStatus(in.String())
			}
		case "condition":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Condition = string(in.String())
			}
		case "min_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinPrice = float64(in.Float64())
			}
		case "max_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxPrice = float64(in.Float64())
			}
		case "levels":
			if in.IsNull() {
				in.Skip()
				out.Levels = nil
			} else {
				in.Delim('[')
				if out.Levels == nil {
					if !in.IsDelim(']') {
						out.Levels = make([]TargetLevel, 0, 1)
					} else {
						out.Levels = []TargetLevel{}
					}
				} else {
					out.Levels = (out.Levels)[:0]
				}
				for !in.IsDelim(']') {
					var v16 TargetLevel
					if in.IsNull() {
						in.Skip()
					} else {
						(v16).UnmarshalEasyJSON(in)
					}
					out.Levels = append(out.Levels, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "confluence":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confluence = ConfluenceGrade(in.String())
			}
		case "geometry":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Geometry = TargetGeometry(in.String())
			}
		case "points":
			if in.IsNull() {
				in.Skip()
				out.Points = nil
			} else {
				in.Delim('[')
				if out.Points == nil {
					if !in.IsDelim(']') {
						out.Points = make([]GeometryPoint, 0, 4)
					} else {
						out.Points = []GeometryPoint{}
					}
				} else {
					out.Points = (out.Points)[:0]
				}
				for !in.IsDelim(']') {
					var v17 GeometryPoint
					if in.IsNull() {
						in.Skip()
					} else {
						(v17).UnmarshalEasyJSON(in)
					}
					out.Points = append(out.Points, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "time_window":
			if in.IsNull() {
				in.Skip()
				out.TimeWindow = nil
			} else {
				if out.TimeWindow == nil {
					out.TimeWindow = new(TimeWindow)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.TimeWindow).UnmarshalEasyJSON(in)
				}
			}
		case "invalidation_ids":
			if in.IsNull() {
				in.Skip()
				out.InvalidationIDs = nil
			} else {
				in.Delim('[')
				if out.InvalidationIDs == nil {
					if !in.IsDelim(']') {
						out.InvalidationIDs = make([]string, 0, 4)
					} else {
						out.InvalidationIDs = []string{}
					}
				} else {
					out.InvalidationIDs = (out.InvalidationIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v18 string
					if in.IsNull() {
						in.Skip()
					} else {
						v18 = string(in.String())
					}
					out.InvalidationIDs = append(out.InvalidationIDs, v18)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave2(out *jwriter.Writer, in TargetZone) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"wave_label\":"
		out.RawString(prefix)
		out.String(string(in.WaveLabel))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"condition\":"
		out.RawString(prefix)
		out.String(string(in.Condition))
	}
	{
		const prefix string = ",\"min_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.MinPrice))
	}
	{
		const prefix string = ",\"max_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.MaxPrice))
	}
	{
		const prefix string = ",\"levels\":"
		out.RawString(prefix)
		if in.Levels == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v19, v20 := range in.Levels {
				if v19 > 0 {
					out.RawByte(',')
				}
				(v20).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"confluence\":"
		out.RawString(prefix)
		out.String(string(in.Confluence))
	}
	{
		const prefix string = ",\"geometry\":"
		out.RawString(prefix)
		out.String(string(in.Geometry))
	}
	if len(in.Points) != 0 {
		const prefix string = ",\"points\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v21, v22 := range in.Points {
				if v21 > 0 {
					out.RawByte(',')
				}
				(v22).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.TimeWindow != nil {
		const prefix string = ",\"time_window\":"
		out.RawString(prefix)
		(*in.TimeWindow).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"invalidation_ids\":"
		out.RawString(prefix)
		if in.InvalidationIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.InvalidationIDs {
				if v23 > 0 {
					out.RawByte(',')
				}
				out.String(string(v24))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TargetZone) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TargetZone) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TargetZone) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TargetZone) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave2(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave3(in *jlexer.Lexer, out *TargetLevel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "relation":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Relation = string(in.String())
			}
		case "family":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Family = string(in.String())
			}
		case "source":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Source = string(in.String())
			}
		case "uncertainty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Uncertainty = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave3(out *jwriter.Writer, in TargetLevel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"relation\":"
		out.RawString(prefix)
		out.String(string(in.Relation))
	}
	{
		const prefix string = ",\"family\":"
		out.RawString(prefix)
		out.String(string(in.Family))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Source))
	}
	{
		const prefix string = ",\"uncertainty\":"
		out.RawString(prefix)
		out.Float64(float64(in.Uncertainty))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TargetLevel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TargetLevel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TargetLevel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TargetLevel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave3(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave4(in *jlexer.Lexer, out *Scenario) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "rank":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rank = int(in.Int())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = ScenarioStatus(in.String())
			}
		case "bias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bias = Direction(in.String())
			}
		case "current_position":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CurrentPosition = string(in.String())
			}
		case "conformance":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Conformance).UnmarshalEasyJSON(in)
			}
		case "invalidations":
			if in.IsNull() {
				in.Skip()
				out.Invalidations = nil
			} else {
				in.Delim('[')
				if out.Invalidations == nil {
					if !in.IsDelim(']') {
						out.Invalidations = make([]Invalidation, 0, 0)
					} else {
						out.Invalidations = []Invalidation{}
					}
				} else {
					out.Invalidations = (out.Invalidations)[:0]
				}
				for !in.IsDelim(']') {
					var v25 Invalidation
					if in.IsNull() {
						in.Skip()
					} else {
						(v25).UnmarshalEasyJSON(in)
					}
					out.Invalidations = append(out.Invalidations, v25)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "root":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Root).UnmarshalEasyJSON(in)
			}
		case "target_ladder":
			if in.IsNull() {
				in.Skip()
				out.TargetLadder = nil
			} else {
				in.Delim('[')
				if out.TargetLadder == nil {
					if !in.IsDelim(']') {
						out.TargetLadder = make([]TargetZone, 0, 0)
					} else {
						out.TargetLadder = []TargetZone{}
					}
				} else {
					out.TargetLadder = (out.TargetLadder)[:0]
				}
				for !in.IsDelim(']') {
					var v26 TargetZone
					if in.IsNull() {
						in.Skip()
					} else {
						(v26).UnmarshalEasyJSON(in)
					}
					out.TargetLadder = append(out.TargetLadder, v26)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave4(out *jwriter.Writer, in Scenario) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"rank\":"
		out.RawString(prefix)
		out.Int(int(in.Rank))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"bias\":"
		out.RawString(prefix)
		out.String(string(in.Bias))
	}
	{
		const prefix string = ",\"current_position\":"
		out.RawString(prefix)
		out.String(string(in.CurrentPosition))
	}
	{
		const prefix string = ",\"conformance\":"
		out.RawString(prefix)
		(in.Conformance).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"invalidations\":"
		out.RawString(prefix)
		if in.Invalidations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v27, v28 := range in.Invalidations {
				if v27 > 0 {
					out.RawByte(',')
				}
				(v28).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"root\":"
		out.RawString(prefix)
		(in.Root).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"target_ladder\":"
		out.RawString(prefix)
		if in.TargetLadder == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v29, v30 := range in.TargetLadder {
				if v29 > 0 {
					out.RawByte(',')
				}
				(v30).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Scenario) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Scenario) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Scenario) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Scenario) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave4(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave5(in *jlexer.Lexer, out *RuleEvaluation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "rule_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RuleID = string(in.String())
			}
		case "class":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Class = RuleClass(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = EvaluationStatus(in.String())
			}
		case "source":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Source = string(in.String())
			}
		case "summary":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Summary = string(in.String())
			}
		case "measured":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Measured = float64(in.Float64())
			}
		case "expected":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Expected = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave5(out *jwriter.Writer, in RuleEvaluation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"rule_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.RuleID))
	}
	{
		const prefix string = ",\"class\":"
		out.RawString(prefix)
		out.String(string(in.Class))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Source))
	}
	{
		const prefix string = ",\"summary\":"
		out.RawString(prefix)
		out.String(string(in.Summary))
	}
	if in.Measured != 0 {
		const prefix string = ",\"measured\":"
		out.RawString(prefix)
		out.Float64(float64(in.Measured))
	}
	if in.Expected != "" {
		const prefix string = ",\"expected\":"
		out.RawString(prefix)
		out.String(string(in.Expected))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RuleEvaluation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RuleEvaluation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RuleEvaluation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RuleEvaluation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave5(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave6(in *jlexer.Lexer, out *Pivot) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "bar_index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BarIndex = int(in.Int())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "kind":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Kind = PivotKind(in.String())
			}
		case "state":
			if in.IsNull() {
				in.Skip()
			} else {
				out.State = PivotState(in.String())
			}
		case "prominence":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Prominence = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave6(out *jwriter.Writer, in Pivot) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"bar_index\":"
		out.RawString(prefix)
		out.Int(int(in.BarIndex))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"kind\":"
		out.RawString(prefix)
		out.String(string(in.Kind))
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.String(string(in.State))
	}
	{
		const prefix string = ",\"prominence\":"
		out.RawString(prefix)
		out.Float64(float64(in.Prominence))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Pivot) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Pivot) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Pivot) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Pivot) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave6(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave7(in *jlexer.Lexer, out *Measurement) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = float64(in.Float64())
			}
		case "unit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Unit = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave7(out *jwriter.Writer, in Measurement) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Float64(float64(in.Value))
	}
	{
		const prefix string = ",\"unit\":"
		out.RawString(prefix)
		out.String(string(in.Unit))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Measurement) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Measurement) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Measurement) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Measurement) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave7(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave8(in *jlexer.Lexer, out *Invalidation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "kind":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Kind = InvalidationKind(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "rule_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RuleID = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave8(out *jwriter.Writer, in Invalidation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"kind\":"
		out.RawString(prefix)
		out.String(string(in.Kind))
	}
	if in.Price != 0 {
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	if in.RuleID != "" {
		const prefix string = ",\"rule_id\":"
		out.RawString(prefix)
		out.String(string(in.RuleID))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Invalidation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Invalidation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Invalidation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Invalidation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave8(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave9(in *jlexer.Lexer, out *GeometryPoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "bar_offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BarOffset = int(in.Int())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave9(out *jwriter.Writer, in GeometryPoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bar_offset\":"
		out.RawString(prefix[1:])
		out.Int(int(in.BarOffset))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GeometryPoint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GeometryPoint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GeometryPoint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GeometryPoint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave9(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave10(in *jlexer.Lexer, out *DataQuality) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "candle_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CandleCount = int(in.Int())
			}
		case "first_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstTime = int64(in.Int64())
			}
		case "last_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastTime = int64(in.Int64())
			}
		case "missing_intervals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MissingIntervals = int(in.Int())
			}
		case "ambiguous_pivot_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AmbiguousPivotCount = int(in.Int())
			}
		case "warnings":
			if in.IsNull() {
				in.Skip()
				out.Warnings = nil
			} else {
				in.Delim('[')
				if out.Warnings == nil {
					if !in.IsDelim(']') {
						out.Warnings = make([]string, 0, 4)
					} else {
						out.Warnings = []string{}
					}
				} else {
					out.Warnings = (out.Warnings)[:0]
				}
				for !in.IsDelim(']') {
					var v31 string
					if in.IsNull() {
						in.Skip()
					} else {
						v31 = string(in.String())
					}
					out.Warnings = append(out.Warnings, v31)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave10(out *jwriter.Writer, in DataQuality) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"candle_count\":"
		out.RawString(prefix[1:])
		out.Int(int(in.CandleCount))
	}
	{
		const prefix string = ",\"first_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.FirstTime))
	}
	{
		const prefix string = ",\"last_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastTime))
	}
	{
		const prefix string = ",\"missing_intervals\":"
		out.RawString(prefix)
		out.Int(int(in.MissingIntervals))
	}
	{
		const prefix string = ",\"ambiguous_pivot_count\":"
		out.RawString(prefix)
		out.Int(int(in.AmbiguousPivotCount))
	}
	if len(in.Warnings) != 0 {
		const prefix string = ",\"warnings\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v32, v33 := range in.Warnings {
				if v32 > 0 {
					out.RawByte(',')
				}
				out.String(string(v33))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DataQuality) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DataQuality) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DataQuality) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DataQuality) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave10(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave11(in *jlexer.Lexer, out *Conformance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "hard_rules_passed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HardRulesPassed = int(in.Int())
			}
		case "hard_rules_failed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HardRulesFailed = int(in.Int())
			}
		case "guidelines_passed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GuidelinesPassed = int(in.Int())
			}
		case "guidelines_failed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GuidelinesFailed = int(in.Int())
			}
		case "not_observable":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NotObservable = int(in.Int())
			}
		case "ratio_confluences":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RatioConfluences = int(in.Int())
			}
		case "structural_coverage":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StructuralCoverage = float64(in.Float64())
			}
		case "score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Score = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave11(out *jwriter.Writer, in Conformance) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"hard_rules_passed\":"
		out.RawString(prefix[1:])
		out.Int(int(in.HardRulesPassed))
	}
	{
		const prefix string = ",\"hard_rules_failed\":"
		out.RawString(prefix)
		out.Int(int(in.HardRulesFailed))
	}
	{
		const prefix string = ",\"guidelines_passed\":"
		out.RawString(prefix)
		out.Int(int(in.GuidelinesPassed))
	}
	{
		const prefix string = ",\"guidelines_failed\":"
		out.RawString(prefix)
		out.Int(int(in.GuidelinesFailed))
	}
	{
		const prefix string = ",\"not_observable\":"
		out.RawString(prefix)
		out.Int(int(in.NotObservable))
	}
	{
		const prefix string = ",\"ratio_confluences\":"
		out.RawString(prefix)
		out.Int(int(in.RatioConfluences))
	}
	{
		const prefix string = ",\"structural_coverage\":"
		out.RawString(prefix)
		out.Float64(float64(in.StructuralCoverage))
	}
	{
		const prefix string = ",\"score\":"
		out.RawString(prefix)
		out.Float64(float64(in.Score))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Conformance) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Conformance) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Conformance) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Conformance) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave11(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave12(in *jlexer.Lexer, out *AnalyzeInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Candles":
			if in.IsNull() {
				in.Skip()
				out.Candles = nil
			} else {
				in.Delim('[')
				if out.Candles == nil {
					if !in.IsDelim(']') {
						out.Candles = make([]market.Candle, 0, 1)
					} else {
						out.Candles = []market.Candle{}
					}
				} else {
					out.Candles = (out.Candles)[:0]
				}
				for !in.IsDelim(']') {
					var v34 market.Candle
					if in.IsNull() {
						in.Skip()
					} else {
						(v34).UnmarshalEasyJSON(in)
					}
					out.Candles = append(out.Candles, v34)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Timeframe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timeframe = market.Timeframe(in.String())
			}
		case "Session":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Session = market.Session(in.String())
			}
		case "MaxScenarios":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxScenarios = int(in.Int())
			}
		case "FutureBars":
			if in.IsNull() {
				in.Skip()
				out.FutureBars = nil
			} else {
				in.Delim('[')
				if out.FutureBars == nil {
					if !in.IsDelim(']') {
						out.FutureBars = make([]int64, 0, 8)
					} else {
						out.FutureBars = []int64{}
					}
				} else {
					out.FutureBars = (out.FutureBars)[:0]
				}
				for !in.IsDelim(']') {
					var v35 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v35 = int64(in.Int64())
					}
					out.FutureBars = append(out.FutureBars, v35)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "TickSize":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TickSize = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave12(out *jwriter.Writer, in AnalyzeInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Candles\":"
		out.RawString(prefix[1:])
		if in.Candles == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v36, v37 := range in.Candles {
				if v36 > 0 {
					out.RawByte(',')
				}
				(v37).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Timeframe\":"
		out.RawString(prefix)
		out.String(string(in.Timeframe))
	}
	{
		const prefix string = ",\"Session\":"
		out.RawString(prefix)
		out.String(string(in.Session))
	}
	{
		const prefix string = ",\"MaxScenarios\":"
		out.RawString(prefix)
		out.Int(int(in.MaxScenarios))
	}
	{
		const prefix string = ",\"FutureBars\":"
		out.RawString(prefix)
		if in.FutureBars == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v38, v39 := range in.FutureBars {
				if v38 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v39))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"TickSize\":"
		out.RawString(prefix)
		out.Float64(float64(in.TickSize))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalyzeInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalyzeInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalyzeInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalyzeInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave12(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainWave13(in *jlexer.Lexer, out *AnalysisResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "data_quality":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.DataQuality).UnmarshalEasyJSON(in)
			}
		case "scenarios":
			if in.IsNull() {
				in.Skip()
				out.Scenarios = nil
			} else {
				in.Delim('[')
				if out.Scenarios == nil {
					if !in.IsDelim(']') {
						out.Scenarios = make([]Scenario, 0, 0)
					} else {
						out.Scenarios = []Scenario{}
					}
				} else {
					out.Scenarios = (out.Scenarios)[:0]
				}
				for !in.IsDelim(']') {
					var v40 Scenario
					if in.IsNull() {
						in.Skip()
					} else {
						(v40).UnmarshalEasyJSON(in)
					}
					out.Scenarios = append(out.Scenarios, v40)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "future_bars":
			if in.IsNull() {
				in.Skip()
				out.FutureBars = nil
			} else {
				in.Delim('[')
				if out.FutureBars == nil {
					if !in.IsDelim(']') {
						out.FutureBars = make([]int64, 0, 8)
					} else {
						out.FutureBars = []int64{}
					}
				} else {
					out.FutureBars = (out.FutureBars)[:0]
				}
				for !in.IsDelim(']') {
					var v41 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v41 = int64(in.Int64())
					}
					out.FutureBars = append(out.FutureBars, v41)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainWave13(out *jwriter.Writer, in AnalysisResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"data_quality\":"
		out.RawString(prefix[1:])
		(in.DataQuality).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"scenarios\":"
		out.RawString(prefix)
		if in.Scenarios == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v42, v43 := range in.Scenarios {
				if v42 > 0 {
					out.RawByte(',')
				}
				(v43).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"future_bars\":"
		out.RawString(prefix)
		if in.FutureBars == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v44, v45 := range in.FutureBars {
				if v44 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v45))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalysisResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainWave13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalysisResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainWave13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalysisResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainWave13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalysisResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainWave13(l, v)
}
