// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package master

import (
	wave "WaveSight/internal/domain/wave"
	market "WaveSight/internal/market"
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeWaveSightInternalDomainMaster(in *jlexer.Lexer, out *ViewManifestItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "timeframe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timeframe = market.Timeframe(in.String())
			}
		case "candle_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CandleCount = int(in.Int())
			}
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = int64(in.Int64())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster(out *jwriter.Writer, in ViewManifestItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"timeframe\":"
		out.RawString(prefix[1:])
		out.String(string(in.Timeframe))
	}
	{
		const prefix string = ",\"candle_count\":"
		out.RawString(prefix)
		out.Int(int(in.CandleCount))
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.Int64(int64(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.Int64(int64(in.To))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ViewManifestItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ViewManifestItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ViewManifestItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ViewManifestItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster1(in *jlexer.Lexer, out *ViewCoverage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = int64(in.Int64())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = int64(in.Int64())
			}
		case "detail_from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DetailFrom = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = CoverageStatus(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster1(out *jwriter.Writer, in ViewCoverage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.Int64(int64(in.To))
	}
	{
		const prefix string = ",\"detail_from\":"
		out.RawString(prefix)
		out.Int64(int64(in.DetailFrom))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ViewCoverage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ViewCoverage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ViewCoverage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ViewCoverage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster1(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster2(in *jlexer.Lexer, out *TimeframeView) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "snapshot_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SnapshotID = string(in.String())
			}
		case "timeframe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timeframe = market.Timeframe(in.String())
			}
		case "candles":
			if in.IsNull() {
				in.Skip()
				out.Candles = nil
			} else {
				in.Delim('[')
				if out.Candles == nil {
					if !in.IsDelim(']') {
						out.Candles = make([]market.DerivedCandle, 0, 0)
					} else {
						out.Candles = []market.DerivedCandle{}
					}
				} else {
					out.Candles = (out.Candles)[:0]
				}
				for !in.IsDelim(']') {
					var v1 market.DerivedCandle
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Candles = append(out.Candles, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "visible_node_ids":
			if in.IsNull() {
				in.Skip()
				out.VisibleNodeIDs = nil
			} else {
				in.Delim('[')
				if out.VisibleNodeIDs == nil {
					if !in.IsDelim(']') {
						out.VisibleNodeIDs = make([]string, 0, 4)
					} else {
						out.VisibleNodeIDs = []string{}
					}
				} else {
					out.VisibleNodeIDs = (out.VisibleNodeIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.VisibleNodeIDs = append(out.VisibleNodeIDs, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ancestor_node_ids":
			if in.IsNull() {
				in.Skip()
				out.AncestorNodeIDs = nil
			} else {
				in.Delim('[')
				if out.AncestorNodeIDs == nil {
					if !in.IsDelim(']') {
						out.AncestorNodeIDs = make([]string, 0, 4)
					} else {
						out.AncestorNodeIDs = []string{}
					}
				} else {
					out.AncestorNodeIDs = (out.AncestorNodeIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					out.AncestorNodeIDs = append(out.AncestorNodeIDs, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "future_logical_bars":
			if in.IsNull() {
				in.Skip()
				out.FutureLogicalBars = nil
			} else {
				in.Delim('[')
				if out.FutureLogicalBars == nil {
					if !in.IsDelim(']') {
						out.FutureLogicalBars = make([]int64, 0, 8)
					} else {
						out.FutureLogicalBars = []int64{}
					}
				} else {
					out.FutureLogicalBars = (out.FutureLogicalBars)[:0]
				}
				for !in.IsDelim(']') {
					var v4 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = int64(in.Int64())
					}
					out.FutureLogicalBars = append(out.FutureLogicalBars, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "coverage":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coverage).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster2(out *jwriter.Writer, in TimeframeView) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"snapshot_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.SnapshotID))
	}
	{
		const prefix string = ",\"timeframe\":"
		out.RawString(prefix)
		out.String(string(in.Timeframe))
	}
	{
		const prefix string = ",\"candles\":"
		out.RawString(prefix)
		if in.Candles == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Candles {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"visible_node_ids\":"
		out.RawString(prefix)
		if in.VisibleNodeIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.VisibleNodeIDs {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ancestor_node_ids\":"
		out.RawString(prefix)
		if in.AncestorNodeIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.AncestorNodeIDs {
				if v9 > 0 {
					out.RawByte(',')
				}
				out.String(string(v10))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"future_logical_bars\":"
		out.RawString(prefix)
		if in.FutureLogicalBars == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.FutureLogicalBars {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v12))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"coverage\":"
		out.RawString(prefix)
		(in.Coverage).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TimeframeView) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TimeframeView) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TimeframeView) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TimeframeView) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster2(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster3(in *jlexer.Lexer, out *TimeframeEvidence) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "timeframe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timeframe = market.Timeframe(in.String())
			}
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Position = string(in.String())
			}
		case "parent_node_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ParentNodeID = string(in.String())
			}
		case "visible_children":
			if in.IsNull() {
				in.Skip()
			} else {
				out.VisibleChildren = int(in.Int())
			}
		case "endpoint_aligned":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndpointAligned = bool(in.Bool())
			}
		case "coverage":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Coverage = CoverageStatus(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster3(out *jwriter.Writer, in TimeframeEvidence) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"timeframe\":"
		out.RawString(prefix[1:])
		out.String(string(in.Timeframe))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.String(string(in.Position))
	}
	if in.ParentNodeID != "" {
		const prefix string = ",\"parent_node_id\":"
		out.RawString(prefix)
		out.String(string(in.ParentNodeID))
	}
	{
		const prefix string = ",\"visible_children\":"
		out.RawString(prefix)
		out.Int(int(in.VisibleChildren))
	}
	{
		const prefix string = ",\"endpoint_aligned\":"
		out.RawString(prefix)
		out.Bool(bool(in.EndpointAligned))
	}
	{
		const prefix string = ",\"coverage\":"
		out.RawString(prefix)
		out.String(string(in.Coverage))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TimeframeEvidence) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TimeframeEvidence) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TimeframeEvidence) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TimeframeEvidence) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster3(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster4(in *jlexer.Lexer, out *SnapshotMetadata) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "parent_snapshot_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ParentSnapshotID = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "session":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Session = market.Session(in.String())
			}
		case "as_of":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AsOf = int64(in.Int64())
			}
		case "generated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GeneratedAt = int64(in.Int64())
			}
		case "focus_timeframe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FocusTimeframe = market.Timeframe(in.String())
			}
		case "theory_version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TheoryVersion = string(in.String())
			}
		case "engine_version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EngineVersion = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster4(out *jwriter.Writer, in SnapshotMetadata) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.ParentSnapshotID != "" {
		const prefix string = ",\"parent_snapshot_id\":"
		out.RawString(prefix)
		out.String(string(in.ParentSnapshotID))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"session\":"
		out.RawString(prefix)
		out.String(string(in.Session))
	}
	{
		const prefix string = ",\"as_of\":"
		out.RawString(prefix)
		out.Int64(int64(in.AsOf))
	}
	{
		const prefix string = ",\"generated_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.GeneratedAt))
	}
	{
		const prefix string = ",\"focus_timeframe\":"
		out.RawString(prefix)
		out.String(string(in.FocusTimeframe))
	}
	{
		const prefix string = ",\"theory_version\":"
		out.RawString(prefix)
		out.String(string(in.TheoryVersion))
	}
	{
		const prefix string = ",\"engine_version\":"
		out.RawString(prefix)
		out.String(string(in.EngineVersion))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SnapshotMetadata) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SnapshotMetadata) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SnapshotMetadata) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SnapshotMetadata) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster4(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster5(in *jlexer.Lexer, out *ScenarioAudit) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "global_thesis":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GlobalThesis = string(in.String())
			}
		case "cross_timeframe_evidence":
			if in.IsNull() {
				in.Skip()
				out.CrossTimeframeEvidence = nil
			} else {
				in.Delim('[')
				if out.CrossTimeframeEvidence == nil {
					if !in.IsDelim(']') {
						out.CrossTimeframeEvidence = make([]TimeframeEvidence, 0, 0)
					} else {
						out.CrossTimeframeEvidence = []TimeframeEvidence{}
					}
				} else {
					out.CrossTimeframeEvidence = (out.CrossTimeframeEvidence)[:0]
				}
				for !in.IsDelim(']') {
					var v13 TimeframeEvidence
					if in.IsNull() {
						in.Skip()
					} else {
						(v13).UnmarshalEasyJSON(in)
					}
					out.CrossTimeframeEvidence = append(out.CrossTimeframeEvidence, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "why_preferred":
			if in.IsNull() {
				in.Skip()
				out.WhyPreferred = nil
			} else {
				if out.WhyPreferred == nil {
					out.WhyPreferred = new(AlternativeComparison)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WhyPreferred).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster5(out *jwriter.Writer, in ScenarioAudit) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"global_thesis\":"
		out.RawString(prefix[1:])
		out.String(string(in.GlobalThesis))
	}
	{
		const prefix string = ",\"cross_timeframe_evidence\":"
		out.RawString(prefix)
		if in.CrossTimeframeEvidence == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.CrossTimeframeEvidence {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.WhyPreferred != nil {
		const prefix string = ",\"why_preferred\":"
		out.RawString(prefix)
		(*in.WhyPreferred).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScenarioAudit) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScenarioAudit) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScenarioAudit) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScenarioAudit) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster5(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster6(in *jlexer.Lexer, out *RefinementRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = string(in.String())
			}
		case "parent_node_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ParentNodeID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster6(out *jwriter.Writer, in RefinementRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix[1:])
		out.String(string(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	if in.ParentNodeID != "" {
		const prefix string = ",\"parent_node_id\":"
		out.RawString(prefix)
		out.String(string(in.ParentNodeID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RefinementRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RefinementRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RefinementRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RefinementRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster6(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster7(in *jlexer.Lexer, out *ProviderQueryTelemetry) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "resolution":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Resolution = NativeResolution(in.String())
			}
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = int64(in.Int64())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = int64(in.Int64())
			}
		case "logical_query":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LogicalQuery = bool(in.Bool())
			}
		case "page_requests":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PageRequests = int(in.Int())
			}
		case "rows":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rows = int(in.Int())
			}
		case "cache_only":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CacheOnly = bool(in.Bool())
			}
		case "overlap_changed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OverlapChanged = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster7(out *jwriter.Writer, in ProviderQueryTelemetry) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"resolution\":"
		out.RawString(prefix[1:])
		out.String(string(in.Resolution))
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.Int64(int64(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.Int64(int64(in.To))
	}
	{
		const prefix string = ",\"logical_query\":"
		out.RawString(prefix)
		out.Bool(bool(in.LogicalQuery))
	}
	{
		const prefix string = ",\"page_requests\":"
		out.RawString(prefix)
		out.Int(int(in.PageRequests))
	}
	{
		const prefix string = ",\"rows\":"
		out.RawString(prefix)
		out.Int(int(in.Rows))
	}
	{
		const prefix string = ",\"cache_only\":"
		out.RawString(prefix)
		out.Bool(bool(in.CacheOnly))
	}
	{
		const prefix string = ",\"overlap_changed\":"
		out.RawString(prefix)
		out.Bool(bool(in.OverlapChanged))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProviderQueryTelemetry) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProviderQueryTelemetry) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProviderQueryTelemetry) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProviderQueryTelemetry) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster7(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster8(in *jlexer.Lexer, out *ObservationRoot) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = int64(in.Int64())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = int64(in.Int64())
			}
		case "open_left_boundary":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OpenLeftBoundary = bool(in.Bool())
			}
		case "context_sequence":
			if in.IsNull() {
				in.Skip()
				out.ContextSequence = nil
			} else {
				in.Delim('[')
				if out.ContextSequence == nil {
					if !in.IsDelim(']') {
						out.ContextSequence = make([]string, 0, 4)
					} else {
						out.ContextSequence = []string{}
					}
				} else {
					out.ContextSequence = (out.ContextSequence)[:0]
				}
				for !in.IsDelim(']') {
					var v16 string
					if in.IsNull() {
						in.Skip()
					} else {
						v16 = string(in.String())
					}
					out.ContextSequence = append(out.ContextSequence, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "intervals":
			if in.IsNull() {
				in.Skip()
				out.Intervals = nil
			} else {
				in.Delim('[')
				if out.Intervals == nil {
					if !in.IsDelim(']') {
						out.Intervals = make([]NarrativeInterval, 0, 1)
					} else {
						out.Intervals = []NarrativeInterval{}
					}
				} else {
					out.Intervals = (out.Intervals)[:0]
				}
				for !in.IsDelim(']') {
					var v17 NarrativeInterval
					if in.IsNull() {
						in.Skip()
					} else {
						(v17).UnmarshalEasyJSON(in)
					}
					out.Intervals = append(out.Intervals, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster8(out *jwriter.Writer, in ObservationRoot) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.Int64(int64(in.To))
	}
	{
		const prefix string = ",\"open_left_boundary\":"
		out.RawString(prefix)
		out.Bool(bool(in.OpenLeftBoundary))
	}
	{
		const prefix string = ",\"context_sequence\":"
		out.RawString(prefix)
		if in.ContextSequence == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.ContextSequence {
				if v18 > 0 {
					out.RawByte(',')
				}
				out.String(string(v19))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"intervals\":"
		out.RawString(prefix)
		if in.Intervals == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Intervals {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ObservationRoot) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ObservationRoot) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ObservationRoot) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ObservationRoot) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster8(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster9(in *jlexer.Lexer, out *NarrativeInterval) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = int64(in.Int64())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = CoverageStatus(in.String())
			}
		case "node_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NodeID = string(in.String())
			}
		case "explanation":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Explanation = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster9(out *jwriter.Writer, in NarrativeInterval) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.Int64(int64(in.To))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.NodeID != "" {
		const prefix string = ",\"node_id\":"
		out.RawString(prefix)
		out.String(string(in.NodeID))
	}
	{
		const prefix string = ",\"explanation\":"
		out.RawString(prefix)
		out.String(string(in.Explanation))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NarrativeInterval) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NarrativeInterval) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NarrativeInterval) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NarrativeInterval) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster9(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster10(in *jlexer.Lexer, out *MasterWaveNode) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "pattern":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Pattern = wave.PatternType(in.String())
			}
		case "mode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Mode = wave.WaveMode(in.String())
			}
		case "function":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Function = wave.WaveFunction(in.String())
			}
		case "direction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Direction = wave.Direction(in.String())
			}
		case "degree":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Degree = wave.Degree(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = wave.WaveStatus(in.String())
			}
		case "label":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Label = string(in.String())
			}
		case "start_event_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartEventID = string(in.String())
			}
		case "end_event_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndEventID = string(in.String())
			}
		case "pivot_event_ids":
			if in.IsNull() {
				in.Skip()
				out.PivotEventIDs = nil
			} else {
				in.Delim('[')
				if out.PivotEventIDs == nil {
					if !in.IsDelim(']') {
						out.PivotEventIDs = make([]string, 0, 4)
					} else {
						out.PivotEventIDs = []string{}
					}
				} else {
					out.PivotEventIDs = (out.PivotEventIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v22 string
					if in.IsNull() {
						in.Skip()
					} else {
						v22 = string(in.String())
					}
					out.PivotEventIDs = append(out.PivotEventIDs, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "child_ids":
			if in.IsNull() {
				in.Skip()
				out.ChildIDs = nil
			} else {
				in.Delim('[')
				if out.ChildIDs == nil {
					if !in.IsDelim(']') {
						out.ChildIDs = make([]string, 0, 4)
					} else {
						out.ChildIDs = []string{}
					}
				} else {
					out.ChildIDs = (out.ChildIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v23 string
					if in.IsNull() {
						in.Skip()
					} else {
						v23 = string(in.String())
					}
					out.ChildIDs = append(out.ChildIDs, v23)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "resolutions":
			if in.IsNull() {
				in.Skip()
				out.Resolutions = nil
			} else {
				in.Delim('[')
				if out.Resolutions == nil {
					if !in.IsDelim(']') {
						out.Resolutions = make([]market.Timeframe, 0, 4)
					} else {
						out.Resolutions = []market.Timeframe{}
					}
				} else {
					out.Resolutions = (out.Resolutions)[:0]
				}
				for !in.IsDelim(']') {
					var v24 market.Timeframe
					if in.IsNull() {
						in.Skip()
					} else {
						v24 = market.Timeframe(in.String())
					}
					out.Resolutions = append(out.Resolutions, v24)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "orthodox_start":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.OrthodoxStart).UnmarshalEasyJSON(in)
			}
		case "orthodox_end":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.OrthodoxEnd).UnmarshalEasyJSON(in)
			}
		case "measurements":
			if in.IsNull() {
				in.Skip()
				out.Measurements = nil
			} else {
				in.Delim('[')
				if out.Measurements == nil {
					if !in.IsDelim(']') {
						out.Measurements = make([]wave.Measurement, 0, 1)
					} else {
						out.Measurements = []wave.Measurement{}
					}
				} else {
					out.Measurements = (out.Measurements)[:0]
				}
				for !in.IsDelim(']') {
					var v25 wave.Measurement
					if in.IsNull() {
						in.Skip()
					} else {
						(v25).UnmarshalEasyJSON(in)
					}
					out.Measurements = append(out.Measurements, v25)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "rule_evaluations":
			if in.IsNull() {
				in.Skip()
				out.RuleEvaluations = nil
			} else {
				in.Delim('[')
				if out.RuleEvaluations == nil {
					if !in.IsDelim(']') {
						out.RuleEvaluations = make([]wave.RuleEvaluation, 0, 0)
					} else {
						out.RuleEvaluations = []wave.RuleEvaluation{}
					}
				} else {
					out.RuleEvaluations = (out.RuleEvaluations)[:0]
				}
				for !in.IsDelim(']') {
					var v26 wave.RuleEvaluation
					if in.IsNull() {
						in.Skip()
					} else {
						(v26).UnmarshalEasyJSON(in)
					}
					out.RuleEvaluations = append(out.RuleEvaluations, v26)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "conformance":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Conformance).UnmarshalEasyJSON(in)
			}
		case "source_node":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.SourceNode).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster10(out *jwriter.Writer, in MasterWaveNode) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"pattern\":"
		out.RawString(prefix)
		out.String(string(in.Pattern))
	}
	{
		const prefix string = ",\"mode\":"
		out.RawString(prefix)
		out.String(string(in.Mode))
	}
	{
		const prefix string = ",\"function\":"
		out.RawString(prefix)
		out.String(string(in.Function))
	}
	{
		const prefix string = ",\"direction\":"
		out.RawString(prefix)
		out.String(string(in.Direction))
	}
	{
		const prefix string = ",\"degree\":"
		out.RawString(prefix)
		out.String(string(in.Degree))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"label\":"
		out.RawString(prefix)
		out.String(string(in.Label))
	}
	{
		const prefix string = ",\"start_event_id\":"
		out.RawString(prefix)
		out.String(string(in.StartEventID))
	}
	{
		const prefix string = ",\"end_event_id\":"
		out.RawString(prefix)
		out.String(string(in.EndEventID))
	}
	{
		const prefix string = ",\"pivot_event_ids\":"
		out.RawString(prefix)
		if in.PivotEventIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v27, v28 := range in.PivotEventIDs {
				if v27 > 0 {
					out.RawByte(',')
				}
				out.String(string(v28))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"child_ids\":"
		out.RawString(prefix)
		if in.ChildIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v29, v30 := range in.ChildIDs {
				if v29 > 0 {
					out.RawByte(',')
				}
				out.String(string(v30))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"resolutions\":"
		out.RawString(prefix)
		if in.Resolutions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v31, v32 := range in.Resolutions {
				if v31 > 0 {
					out.RawByte(',')
				}
				out.String(string(v32))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"orthodox_start\":"
		out.RawString(prefix)
		(in.OrthodoxStart).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"orthodox_end\":"
		out.RawString(prefix)
		(in.OrthodoxEnd).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"measurements\":"
		out.RawString(prefix)
		if in.Measurements == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v33, v34 := range in.Measurements {
				if v33 > 0 {
					out.RawByte(',')
				}
				(v34).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"rule_evaluations\":"
		out.RawString(prefix)
		if in.RuleEvaluations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v35, v36 := range in.RuleEvaluations {
				if v35 > 0 {
					out.RawByte(',')
				}
				(v36).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"conformance\":"
		out.RawString(prefix)
		(in.Conformance).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"source_node\":"
		out.RawString(prefix)
		(in.SourceNode).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MasterWaveNode) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MasterWaveNode) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MasterWaveNode) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MasterWaveNode) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster10(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster11(in *jlexer.Lexer, out *MasterWaveGraph) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "events":
			if in.IsNull() {
				in.Skip()
				out.Events = nil
			} else {
				in.Delim('[')
				if out.Events == nil {
					if !in.IsDelim(']') {
						out.Events = make([]CanonicalWaveEvent, 0, 0)
					} else {
						out.Events = []CanonicalWaveEvent{}
					}
				} else {
					out.Events = (out.Events)[:0]
				}
				for !in.IsDelim(']') {
					var v37 CanonicalWaveEvent
					if in.IsNull() {
						in.Skip()
					} else {
						(v37).UnmarshalEasyJSON(in)
					}
					out.Events = append(out.Events, v37)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "nodes":
			if in.IsNull() {
				in.Skip()
				out.Nodes = nil
			} else {
				in.Delim('[')
				if out.Nodes == nil {
					if !in.IsDelim(']') {
						out.Nodes = make([]MasterWaveNode, 0, 0)
					} else {
						out.Nodes = []MasterWaveNode{}
					}
				} else {
					out.Nodes = (out.Nodes)[:0]
				}
				for !in.IsDelim(']') {
					var v38 MasterWaveNode
					if in.IsNull() {
						in.Skip()
					} else {
						(v38).UnmarshalEasyJSON(in)
					}
					out.Nodes = append(out.Nodes, v38)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster11(out *jwriter.Writer, in MasterWaveGraph) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"events\":"
		out.RawString(prefix[1:])
		if in.Events == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v39, v40 := range in.Events {
				if v39 > 0 {
					out.RawByte(',')
				}
				(v40).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"nodes\":"
		out.RawString(prefix)
		if in.Nodes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v41, v42 := range in.Nodes {
				if v41 > 0 {
					out.RawByte(',')
				}
				(v42).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MasterWaveGraph) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MasterWaveGraph) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MasterWaveGraph) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MasterWaveGraph) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster11(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster12(in *jlexer.Lexer, out *MasterScenario) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "rank":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rank = int(in.Int())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = wave.ScenarioStatus(in.String())
			}
		case "bias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bias = wave.Direction(in.String())
			}
		case "current_position":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CurrentPosition = string(in.String())
			}
		case "conformance":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Conformance).UnmarshalEasyJSON(in)
			}
		case "observation_root":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.ObservationRoot).UnmarshalEasyJSON(in)
			}
		case "active_path":
			if in.IsNull() {
				in.Skip()
				out.ActivePath = nil
			} else {
				in.Delim('[')
				if out.ActivePath == nil {
					if !in.IsDelim(']') {
						out.ActivePath = make([]string, 0, 4)
					} else {
						out.ActivePath = []string{}
					}
				} else {
					out.ActivePath = (out.ActivePath)[:0]
				}
				for !in.IsDelim(']') {
					var v43 string
					if in.IsNull() {
						in.Skip()
					} else {
						v43 = string(in.String())
					}
					out.ActivePath = append(out.ActivePath, v43)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "invalidations":
			if in.IsNull() {
				in.Skip()
				out.Invalidations = nil
			} else {
				in.Delim('[')
				if out.Invalidations == nil {
					if !in.IsDelim(']') {
						out.Invalidations = make([]wave.Invalidation, 0, 0)
					} else {
						out.Invalidations = []wave.Invalidation{}
					}
				} else {
					out.Invalidations = (out.Invalidations)[:0]
				}
				for !in.IsDelim(']') {
					var v44 wave.Invalidation
					if in.IsNull() {
						in.Skip()
					} else {
						(v44).UnmarshalEasyJSON(in)
					}
					out.Invalidations = append(out.Invalidations, v44)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "target_ladder":
			if in.IsNull() {
				in.Skip()
				out.TargetLadder = nil
			} else {
				in.Delim('[')
				if out.TargetLadder == nil {
					if !in.IsDelim(']') {
						out.TargetLadder = make([]wave.TargetZone, 0, 0)
					} else {
						out.TargetLadder = []wave.TargetZone{}
					}
				} else {
					out.TargetLadder = (out.TargetLadder)[:0]
				}
				for !in.IsDelim(']') {
					var v45 wave.TargetZone
					if in.IsNull() {
						in.Skip()
					} else {
						(v45).UnmarshalEasyJSON(in)
					}
					out.TargetLadder = append(out.TargetLadder, v45)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "audit":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Audit).UnmarshalEasyJSON(in)
			}
		case "material_signature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaterialSignature = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster12(out *jwriter.Writer, in MasterScenario) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"rank\":"
		out.RawString(prefix)
		out.Int(int(in.Rank))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"bias\":"
		out.RawString(prefix)
		out.String(string(in.Bias))
	}
	{
		const prefix string = ",\"current_position\":"
		out.RawString(prefix)
		out.String(string(in.CurrentPosition))
	}
	{
		const prefix string = ",\"conformance\":"
		out.RawString(prefix)
		(in.Conformance).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"observation_root\":"
		out.RawString(prefix)
		(in.ObservationRoot).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"active_path\":"
		out.RawString(prefix)
		if in.ActivePath == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v46, v47 := range in.ActivePath {
				if v46 > 0 {
					out.RawByte(',')
				}
				out.String(string(v47))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"invalidations\":"
		out.RawString(prefix)
		if in.Invalidations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v48, v49 := range in.Invalidations {
				if v48 > 0 {
					out.RawByte(',')
				}
				(v49).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"target_ladder\":"
		out.RawString(prefix)
		if in.TargetLadder == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v50, v51 := range in.TargetLadder {
				if v50 > 0 {
					out.RawByte(',')
				}
				(v51).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"audit\":"
		out.RawString(prefix)
		(in.Audit).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"material_signature\":"
		out.RawString(prefix)
		out.String(string(in.MaterialSignature))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MasterScenario) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MasterScenario) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MasterScenario) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MasterScenario) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster12(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster13(in *jlexer.Lexer, out *EventSource) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "timeframe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timeframe = market.Timeframe(in.String())
			}
		case "bar_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BarTime = int64(in.Int64())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "provenance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Provenance = market.BarProvenance(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster13(out *jwriter.Writer, in EventSource) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"timeframe\":"
		out.RawString(prefix[1:])
		out.String(string(in.Timeframe))
	}
	{
		const prefix string = ",\"bar_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.BarTime))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"provenance\":"
		out.RawString(prefix)
		out.String(string(in.Provenance))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EventSource) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventSource) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventSource) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventSource) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster13(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster14(in *jlexer.Lexer, out *DatasetManifest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "coverage":
			if in.IsNull() {
				in.Skip()
				out.Coverage = nil
			} else {
				in.Delim('[')
				if out.Coverage == nil {
					if !in.IsDelim(']') {
						out.Coverage = make([]CoverageInterval, 0, 1)
					} else {
						out.Coverage = []CoverageInterval{}
					}
				} else {
					out.Coverage = (out.Coverage)[:0]
				}
				for !in.IsDelim(']') {
					var v52 CoverageInterval
					if in.IsNull() {
						in.Skip()
					} else {
						(v52).UnmarshalEasyJSON(in)
					}
					out.Coverage = append(out.Coverage, v52)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "provider_queries":
			if in.IsNull() {
				in.Skip()
				out.ProviderQueries = nil
			} else {
				in.Delim('[')
				if out.ProviderQueries == nil {
					if !in.IsDelim(']') {
						out.ProviderQueries = make([]ProviderQueryTelemetry, 0, 1)
					} else {
						out.ProviderQueries = []ProviderQueryTelemetry{}
					}
				} else {
					out.ProviderQueries = (out.ProviderQueries)[:0]
				}
				for !in.IsDelim(']') {
					var v53 ProviderQueryTelemetry
					if in.IsNull() {
						in.Skip()
					} else {
						(v53).UnmarshalEasyJSON(in)
					}
					out.ProviderQueries = append(out.ProviderQueries, v53)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "daily_provenance":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.DailyProvenance).UnmarshalEasyJSON(in)
			}
		case "minute_detail_from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinuteDetailFrom = int64(in.Int64())
			}
		case "minute_detail_to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinuteDetailTo = int64(in.Int64())
			}
		case "native_daily_rows":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NativeDailyRows = int(in.Int())
			}
		case "native_minute_rows":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NativeMinuteRows = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster14(out *jwriter.Writer, in DatasetManifest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coverage\":"
		out.RawString(prefix[1:])
		if in.Coverage == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v54, v55 := range in.Coverage {
				if v54 > 0 {
					out.RawByte(',')
				}
				(v55).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"provider_queries\":"
		out.RawString(prefix)
		if in.ProviderQueries == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v56, v57 := range in.ProviderQueries {
				if v56 > 0 {
					out.RawByte(',')
				}
				(v57).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"daily_provenance\":"
		out.RawString(prefix)
		(in.DailyProvenance).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"minute_detail_from\":"
		out.RawString(prefix)
		out.Int64(int64(in.MinuteDetailFrom))
	}
	{
		const prefix string = ",\"minute_detail_to\":"
		out.RawString(prefix)
		out.Int64(int64(in.MinuteDetailTo))
	}
	{
		const prefix string = ",\"native_daily_rows\":"
		out.RawString(prefix)
		out.Int(int(in.NativeDailyRows))
	}
	{
		const prefix string = ",\"native_minute_rows\":"
		out.RawString(prefix)
		out.Int(int(in.NativeMinuteRows))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DatasetManifest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DatasetManifest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DatasetManifest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DatasetManifest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster14(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster15(in *jlexer.Lexer, out *DailyProvenanceAudit) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "compared":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Compared = int(in.Int())
			}
		case "differences":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Differences = int(in.Int())
			}
		case "max_ohlc_deviation":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxOHLCDeviation = float64(in.Float64())
			}
		case "samples":
			if in.IsNull() {
				in.Skip()
				out.Samples = nil
			} else {
				in.Delim('[')
				if out.Samples == nil {
					if !in.IsDelim(']') {
						out.Samples = make([]DailyBarDifference, 0, 1)
					} else {
						out.Samples = []DailyBarDifference{}
					}
				} else {
					out.Samples = (out.Samples)[:0]
				}
				for !in.IsDelim(']') {
					var v58 DailyBarDifference
					if in.IsNull() {
						in.Skip()
					} else {
						(v58).UnmarshalEasyJSON(in)
					}
					out.Samples = append(out.Samples, v58)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster15(out *jwriter.Writer, in DailyProvenanceAudit) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"compared\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Compared))
	}
	{
		const prefix string = ",\"differences\":"
		out.RawString(prefix)
		out.Int(int(in.Differences))
	}
	{
		const prefix string = ",\"max_ohlc_deviation\":"
		out.RawString(prefix)
		out.Float64(float64(in.MaxOHLCDeviation))
	}
	{
		const prefix string = ",\"samples\":"
		out.RawString(prefix)
		if in.Samples == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v59, v60 := range in.Samples {
				if v59 > 0 {
					out.RawByte(',')
				}
				(v60).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DailyProvenanceAudit) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DailyProvenanceAudit) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DailyProvenanceAudit) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DailyProvenanceAudit) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster15(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster16(in *jlexer.Lexer, out *DailyBarDifference) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = string(in.String())
			}
		case "native_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NativeTime = int64(in.Int64())
			}
		case "derived_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DerivedTime = int64(in.Int64())
			}
		case "max_ohlc_deviation":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxOHLCDeviation = float64(in.Float64())
			}
		case "volume_deviation":
			if in.IsNull() {
				in.Skip()
			} else {
				out.VolumeDeviation = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster16(out *jwriter.Writer, in DailyBarDifference) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix[1:])
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"native_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.NativeTime))
	}
	{
		const prefix string = ",\"derived_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.DerivedTime))
	}
	{
		const prefix string = ",\"max_ohlc_deviation\":"
		out.RawString(prefix)
		out.Float64(float64(in.MaxOHLCDeviation))
	}
	{
		const prefix string = ",\"volume_deviation\":"
		out.RawString(prefix)
		out.Float64(float64(in.VolumeDeviation))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DailyBarDifference) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DailyBarDifference) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DailyBarDifference) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DailyBarDifference) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster16(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster17(in *jlexer.Lexer, out *CoverageInterval) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "resolution":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Resolution = NativeResolution(in.String())
			}
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = int64(in.Int64())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = int64(in.Int64())
			}
		case "complete":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Complete = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster17(out *jwriter.Writer, in CoverageInterval) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"resolution\":"
		out.RawString(prefix[1:])
		out.String(string(in.Resolution))
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.Int64(int64(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.Int64(int64(in.To))
	}
	{
		const prefix string = ",\"complete\":"
		out.RawString(prefix)
		out.Bool(bool(in.Complete))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CoverageInterval) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CoverageInterval) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CoverageInterval) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CoverageInterval) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster17(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster18(in *jlexer.Lexer, out *CanonicalWaveEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "kind":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Kind = wave.PivotKind(in.String())
			}
		case "state":
			if in.IsNull() {
				in.Skip()
			} else {
				out.State = EventState(in.String())
			}
		case "time_from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TimeFrom = int64(in.Int64())
			}
		case "time_to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TimeTo = int64(in.Int64())
			}
		case "orthodox_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OrthodoxTime = int64(in.Int64())
			}
		case "orthodox_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OrthodoxPrice = float64(in.Float64())
			}
		case "resolutions":
			if in.IsNull() {
				in.Skip()
				out.Resolutions = nil
			} else {
				in.Delim('[')
				if out.Resolutions == nil {
					if !in.IsDelim(']') {
						out.Resolutions = make([]market.Timeframe, 0, 4)
					} else {
						out.Resolutions = []market.Timeframe{}
					}
				} else {
					out.Resolutions = (out.Resolutions)[:0]
				}
				for !in.IsDelim(']') {
					var v61 market.Timeframe
					if in.IsNull() {
						in.Skip()
					} else {
						v61 = market.Timeframe(in.String())
					}
					out.Resolutions = append(out.Resolutions, v61)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "sources":
			if in.IsNull() {
				in.Skip()
				out.Sources = nil
			} else {
				in.Delim('[')
				if out.Sources == nil {
					if !in.IsDelim(']') {
						out.Sources = make([]EventSource, 0, 1)
					} else {
						out.Sources = []EventSource{}
					}
				} else {
					out.Sources = (out.Sources)[:0]
				}
				for !in.IsDelim(']') {
					var v62 EventSource
					if in.IsNull() {
						in.Skip()
					} else {
						(v62).UnmarshalEasyJSON(in)
					}
					out.Sources = append(out.Sources, v62)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "max_price_delta":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxPriceDelta = float64(in.Float64())
			}
		case "max_time_delta":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxTimeDelta = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster18(out *jwriter.Writer, in CanonicalWaveEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"kind\":"
		out.RawString(prefix)
		out.String(string(in.Kind))
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.String(string(in.State))
	}
	{
		const prefix string = ",\"time_from\":"
		out.RawString(prefix)
		out.Int64(int64(in.TimeFrom))
	}
	{
		const prefix string = ",\"time_to\":"
		out.RawString(prefix)
		out.Int64(int64(in.TimeTo))
	}
	{
		const prefix string = ",\"orthodox_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.OrthodoxTime))
	}
	{
		const prefix string = ",\"orthodox_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.OrthodoxPrice))
	}
	{
		const prefix string = ",\"resolutions\":"
		out.RawString(prefix)
		if in.Resolutions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v63, v64 := range in.Resolutions {
				if v63 > 0 {
					out.RawByte(',')
				}
				out.String(string(v64))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"sources\":"
		out.RawString(prefix)
		if in.Sources == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v65, v66 := range in.Sources {
				if v65 > 0 {
					out.RawByte(',')
				}
				(v66).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"max_price_delta\":"
		out.RawString(prefix)
		out.Float64(float64(in.MaxPriceDelta))
	}
	{
		const prefix string = ",\"max_time_delta\":"
		out.RawString(prefix)
		out.Int64(int64(in.MaxTimeDelta))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CanonicalWaveEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster18(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CanonicalWaveEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster18(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CanonicalWaveEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster18(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CanonicalWaveEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster18(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster19(in *jlexer.Lexer, out *AnalysisSnapshot) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "parent_snapshot_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ParentSnapshotID = string(in.String())
			}
		case "theory_version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TheoryVersion = string(in.String())
			}
		case "engine_version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EngineVersion = string(in.String())
			}
		case "generated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GeneratedAt = int64(in.Int64())
			}
		case "request":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Request).UnmarshalEasyJSON(in)
			}
		case "dataset_manifest":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.DatasetManifest).UnmarshalEasyJSON(in)
			}
		case "master_wave_graph":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Graph).UnmarshalEasyJSON(in)
			}
		case "scenarios":
			if in.IsNull() {
				in.Skip()
				out.Scenarios = nil
			} else {
				in.Delim('[')
				if out.Scenarios == nil {
					if !in.IsDelim(']') {
						out.Scenarios = make([]MasterScenario, 0, 0)
					} else {
						out.Scenarios = []MasterScenario{}
					}
				} else {
					out.Scenarios = (out.Scenarios)[:0]
				}
				for !in.IsDelim(']') {
					var v67 MasterScenario
					if in.IsNull() {
						in.Skip()
					} else {
						(v67).UnmarshalEasyJSON(in)
					}
					out.Scenarios = append(out.Scenarios, v67)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "view_manifest":
			if in.IsNull() {
				in.Skip()
				out.ViewManifest = nil
			} else {
				in.Delim('[')
				if out.ViewManifest == nil {
					if !in.IsDelim(']') {
						out.ViewManifest = make([]ViewManifestItem, 0, 1)
					} else {
						out.ViewManifest = []ViewManifestItem{}
					}
				} else {
					out.ViewManifest = (out.ViewManifest)[:0]
				}
				for !in.IsDelim(']') {
					var v68 ViewManifestItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v68).UnmarshalEasyJSON(in)
					}
					out.ViewManifest = append(out.ViewManifest, v68)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "initial_view":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.InitialView).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster19(out *jwriter.Writer, in AnalysisSnapshot) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.ParentSnapshotID != "" {
		const prefix string = ",\"parent_snapshot_id\":"
		out.RawString(prefix)
		out.String(string(in.ParentSnapshotID))
	}
	{
		const prefix string = ",\"theory_version\":"
		out.RawString(prefix)
		out.String(string(in.TheoryVersion))
	}
	{
		const prefix string = ",\"engine_version\":"
		out.RawString(prefix)
		out.String(string(in.EngineVersion))
	}
	{
		const prefix string = ",\"generated_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.GeneratedAt))
	}
	{
		const prefix string = ",\"request\":"
		out.RawString(prefix)
		(in.Request).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"dataset_manifest\":"
		out.RawString(prefix)
		(in.DatasetManifest).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"master_wave_graph\":"
		out.RawString(prefix)
		(in.Graph).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"scenarios\":"
		out.RawString(prefix)
		if in.Scenarios == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v69, v70 := range in.Scenarios {
				if v69 > 0 {
					out.RawByte(',')
				}
				(v70).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"view_manifest\":"
		out.RawString(prefix)
		if in.ViewManifest == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v71, v72 := range in.ViewManifest {
				if v71 > 0 {
					out.RawByte(',')
				}
				(v72).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"initial_view\":"
		out.RawString(prefix)
		(in.InitialView).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalysisSnapshot) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster19(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalysisSnapshot) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster19(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalysisSnapshot) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster19(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalysisSnapshot) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster19(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster20(in *jlexer.Lexer, out *AnalysisRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "session":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Session = market.Session(in.String())
			}
		case "as_of":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AsOf = string(in.String())
			}
		case "focus_timeframe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FocusTimeframe = market.Timeframe(in.String())
			}
		case "history_profile":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HistoryProfile = HistoryProfile(in.String())
			}
		case "max_scenarios":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxScenarios = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster20(out *jwriter.Writer, in AnalysisRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"session\":"
		out.RawString(prefix)
		out.String(string(in.Session))
	}
	{
		const prefix string = ",\"as_of\":"
		out.RawString(prefix)
		out.String(string(in.AsOf))
	}
	{
		const prefix string = ",\"focus_timeframe\":"
		out.RawString(prefix)
		out.String(string(in.FocusTimeframe))
	}
	{
		const prefix string = ",\"history_profile\":"
		out.RawString(prefix)
		out.String(string(in.HistoryProfile))
	}
	{
		const prefix string = ",\"max_scenarios\":"
		out.RawString(prefix)
		out.Int(int(in.MaxScenarios))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalysisRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster20(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalysisRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster20(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalysisRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster20(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalysisRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster20(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster21(in *jlexer.Lexer, out *AnalysisJob) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = JobStatus(in.String())
			}
		case "progress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Progress = int(in.Int())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "snapshot_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SnapshotID = string(in.String())
			}
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Error = string(in.String())
			}
		case "request":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Request).UnmarshalEasyJSON(in)
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = int64(in.Int64())
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpdatedAt = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster21(out *jwriter.Writer, in AnalysisJob) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"progress\":"
		out.RawString(prefix)
		out.Int(int(in.Progress))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	if in.SnapshotID != "" {
		const prefix string = ",\"snapshot_id\":"
		out.RawString(prefix)
		out.String(string(in.SnapshotID))
	}
	if in.Error != "" {
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	{
		const prefix string = ",\"request\":"
		out.RawString(prefix)
		(in.Request).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreatedAt))
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalysisJob) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster21(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalysisJob) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster21(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalysisJob) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster21(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalysisJob) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster21(l, v)
}
func easyjson6601e8cdDecodeWaveSightInternalDomainMaster22(in *jlexer.Lexer, out *AlternativeComparison) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "alternative_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AlternativeID = string(in.String())
			}
		case "first_divergence":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstDivergence = string(in.String())
			}
		case "preferred_evidence":
			if in.IsNull() {
				in.Skip()
				out.PreferredEvidence = nil
			} else {
				in.Delim('[')
				if out.PreferredEvidence == nil {
					if !in.IsDelim(']') {
						out.PreferredEvidence = make([]string, 0, 4)
					} else {
						out.PreferredEvidence = []string{}
					}
				} else {
					out.PreferredEvidence = (out.PreferredEvidence)[:0]
				}
				for !in.IsDelim(']') {
					var v73 string
					if in.IsNull() {
						in.Skip()
					} else {
						v73 = string(in.String())
					}
					out.PreferredEvidence = append(out.PreferredEvidence, v73)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "different_targets":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DifferentTargets = bool(in.Bool())
			}
		case "different_bias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DifferentBias = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeWaveSightInternalDomainMaster22(out *jwriter.Writer, in AlternativeComparison) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alternative_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.AlternativeID))
	}
	{
		const prefix string = ",\"first_divergence\":"
		out.RawString(prefix)
		out.String(string(in.FirstDivergence))
	}
	{
		const prefix string = ",\"preferred_evidence\":"
		out.RawString(prefix)
		if in.PreferredEvidence == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v74, v75 := range in.PreferredEvidence {
				if v74 > 0 {
					out.RawByte(',')
				}
				out.String(string(v75))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"different_targets\":"
		out.RawString(prefix)
		out.Bool(bool(in.DifferentTargets))
	}
	{
		const prefix string = ",\"different_bias\":"
		out.RawString(prefix)
		out.Bool(bool(in.DifferentBias))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AlternativeComparison) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster22(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AlternativeComparison) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeWaveSightInternalDomainMaster22(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AlternativeComparison) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster22(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AlternativeComparison) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeWaveSightInternalDomainMaster22(l, v)
}
