// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB04a0c2DecodeWaveSightPkgModel(in *jlexer.Lexer, out *CorrectiveWave) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start":
			if in.IsNull() {
				in.Skip()
				out.Start = nil
			} else {
				if out.Start == nil {
					out.Start = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Start).UnmarshalEasyJSON(in)
				}
			}
		case "wa":
			if in.IsNull() {
				in.Skip()
				out.WA = nil
			} else {
				if out.WA == nil {
					out.WA = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WA).UnmarshalEasyJSON(in)
				}
			}
		case "wb":
			if in.IsNull() {
				in.Skip()
				out.WB = nil
			} else {
				if out.WB == nil {
					out.WB = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WB).UnmarshalEasyJSON(in)
				}
			}
		case "wc":
			if in.IsNull() {
				in.Skip()
				out.WC = nil
			} else {
				if out.WC == nil {
					out.WC = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WC).UnmarshalEasyJSON(in)
				}
			}
		case "wd":
			if in.IsNull() {
				in.Skip()
				out.WD = nil
			} else {
				if out.WD == nil {
					out.WD = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WD).UnmarshalEasyJSON(in)
				}
			}
		case "we":
			if in.IsNull() {
				in.Skip()
				out.WE = nil
			} else {
				if out.WE == nil {
					out.WE = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WE).UnmarshalEasyJSON(in)
				}
			}
		case "wx":
			if in.IsNull() {
				in.Skip()
				out.WX = nil
			} else {
				if out.WX == nil {
					out.WX = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WX).UnmarshalEasyJSON(in)
				}
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "direction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Direction = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB04a0c2EncodeWaveSightPkgModel(out *jwriter.Writer, in CorrectiveWave) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start\":"
		out.RawString(prefix[1:])
		if in.Start == nil {
			out.RawString("null")
		} else {
			(*in.Start).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"wa\":"
		out.RawString(prefix)
		if in.WA == nil {
			out.RawString("null")
		} else {
			(*in.WA).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"wb\":"
		out.RawString(prefix)
		if in.WB == nil {
			out.RawString("null")
		} else {
			(*in.WB).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"wc\":"
		out.RawString(prefix)
		if in.WC == nil {
			out.RawString("null")
		} else {
			(*in.WC).MarshalEasyJSON(out)
		}
	}
	if in.WD != nil {
		const prefix string = ",\"wd\":"
		out.RawString(prefix)
		(*in.WD).MarshalEasyJSON(out)
	}
	if in.WE != nil {
		const prefix string = ",\"we\":"
		out.RawString(prefix)
		(*in.WE).MarshalEasyJSON(out)
	}
	if in.WX != nil {
		const prefix string = ",\"wx\":"
		out.RawString(prefix)
		(*in.WX).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"direction\":"
		out.RawString(prefix)
		out.String(string(in.Direction))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CorrectiveWave) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB04a0c2EncodeWaveSightPkgModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CorrectiveWave) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB04a0c2EncodeWaveSightPkgModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CorrectiveWave) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB04a0c2DecodeWaveSightPkgModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CorrectiveWave) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB04a0c2DecodeWaveSightPkgModel(l, v)
}
