// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB04a0c2DecodeWaveSightPkgModel(in *jlexer.Lexer, out *CorrectiveWave) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start":
			if in.IsNull() {
				in.Skip()
				out.Start = nil
			} else {
				if out.Start == nil {
					out.Start = new(Pivot)
				}
				easyjsonB04a0c2DecodeWaveSightPkgModel1(in, out.Start)
			}
		case "wa":
			if in.IsNull() {
				in.Skip()
				out.WA = nil
			} else {
				if out.WA == nil {
					out.WA = new(Pivot)
				}
				easyjsonB04a0c2DecodeWaveSightPkgModel1(in, out.WA)
			}
		case "wb":
			if in.IsNull() {
				in.Skip()
				out.WB = nil
			} else {
				if out.WB == nil {
					out.WB = new(Pivot)
				}
				easyjsonB04a0c2DecodeWaveSightPkgModel1(in, out.WB)
			}
		case "wc":
			if in.IsNull() {
				in.Skip()
				out.WC = nil
			} else {
				if out.WC == nil {
					out.WC = new(Pivot)
				}
				easyjsonB04a0c2DecodeWaveSightPkgModel1(in, out.WC)
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "direction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Direction = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB04a0c2EncodeWaveSightPkgModel(out *jwriter.Writer, in CorrectiveWave) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start\":"
		out.RawString(prefix[1:])
		if in.Start == nil {
			out.RawString("null")
		} else {
			easyjsonB04a0c2EncodeWaveSightPkgModel1(out, *in.Start)
		}
	}
	{
		const prefix string = ",\"wa\":"
		out.RawString(prefix)
		if in.WA == nil {
			out.RawString("null")
		} else {
			easyjsonB04a0c2EncodeWaveSightPkgModel1(out, *in.WA)
		}
	}
	{
		const prefix string = ",\"wb\":"
		out.RawString(prefix)
		if in.WB == nil {
			out.RawString("null")
		} else {
			easyjsonB04a0c2EncodeWaveSightPkgModel1(out, *in.WB)
		}
	}
	{
		const prefix string = ",\"wc\":"
		out.RawString(prefix)
		if in.WC == nil {
			out.RawString("null")
		} else {
			easyjsonB04a0c2EncodeWaveSightPkgModel1(out, *in.WC)
		}
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"direction\":"
		out.RawString(prefix)
		out.String(string(in.Direction))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CorrectiveWave) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB04a0c2EncodeWaveSightPkgModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CorrectiveWave) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB04a0c2EncodeWaveSightPkgModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CorrectiveWave) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB04a0c2DecodeWaveSightPkgModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CorrectiveWave) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB04a0c2DecodeWaveSightPkgModel(l, v)
}
func easyjsonB04a0c2DecodeWaveSightPkgModel1(in *jlexer.Lexer, out *Pivot) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = PivotType(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB04a0c2EncodeWaveSightPkgModel1(out *jwriter.Writer, in Pivot) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	out.RawByte('}')
}
