// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson67127156DecodeWaveSightPkgModel(in *jlexer.Lexer, out *IncompleteWave) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start":
			if in.IsNull() {
				in.Skip()
				out.Start = nil
			} else {
				if out.Start == nil {
					out.Start = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Start).UnmarshalEasyJSON(in)
				}
			}
		case "w1":
			if in.IsNull() {
				in.Skip()
				out.W1 = nil
			} else {
				if out.W1 == nil {
					out.W1 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W1).UnmarshalEasyJSON(in)
				}
			}
		case "w2":
			if in.IsNull() {
				in.Skip()
				out.W2 = nil
			} else {
				if out.W2 == nil {
					out.W2 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W2).UnmarshalEasyJSON(in)
				}
			}
		case "w3":
			if in.IsNull() {
				in.Skip()
				out.W3 = nil
			} else {
				if out.W3 == nil {
					out.W3 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W3).UnmarshalEasyJSON(in)
				}
			}
		case "direction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Direction = string(in.String())
			}
		case "confidence_score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfidenceScore = float64(in.Float64())
			}
		case "target_box":
			if in.IsNull() {
				in.Skip()
				out.TargetBox = nil
			} else {
				if out.TargetBox == nil {
					out.TargetBox = new(TargetBox)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.TargetBox).UnmarshalEasyJSON(in)
				}
			}
		case "degree":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Degree = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson67127156EncodeWaveSightPkgModel(out *jwriter.Writer, in IncompleteWave) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start\":"
		out.RawString(prefix[1:])
		if in.Start == nil {
			out.RawString("null")
		} else {
			(*in.Start).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w1\":"
		out.RawString(prefix)
		if in.W1 == nil {
			out.RawString("null")
		} else {
			(*in.W1).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w2\":"
		out.RawString(prefix)
		if in.W2 == nil {
			out.RawString("null")
		} else {
			(*in.W2).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w3\":"
		out.RawString(prefix)
		if in.W3 == nil {
			out.RawString("null")
		} else {
			(*in.W3).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"direction\":"
		out.RawString(prefix)
		out.String(string(in.Direction))
	}
	{
		const prefix string = ",\"confidence_score\":"
		out.RawString(prefix)
		out.Float64(float64(in.ConfidenceScore))
	}
	if in.TargetBox != nil {
		const prefix string = ",\"target_box\":"
		out.RawString(prefix)
		(*in.TargetBox).MarshalEasyJSON(out)
	}
	if in.Degree != "" {
		const prefix string = ",\"degree\":"
		out.RawString(prefix)
		out.String(string(in.Degree))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IncompleteWave) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson67127156EncodeWaveSightPkgModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IncompleteWave) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson67127156EncodeWaveSightPkgModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IncompleteWave) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson67127156DecodeWaveSightPkgModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IncompleteWave) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson67127156DecodeWaveSightPkgModel(l, v)
}
