// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC80ae7adDecodeWaveSightPkgModel(in *jlexer.Lexer, out *WaveStructure) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "pivots":
			if in.IsNull() {
				in.Skip()
				out.Pivots = nil
			} else {
				in.Delim('[')
				if out.Pivots == nil {
					if !in.IsDelim(']') {
						out.Pivots = make([]Pivot, 0, 2)
					} else {
						out.Pivots = []Pivot{}
					}
				} else {
					out.Pivots = (out.Pivots)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Pivot
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Pivots = append(out.Pivots, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "purple_boxes":
			if in.IsNull() {
				in.Skip()
				out.PurpleBoxes = nil
			} else {
				in.Delim('[')
				if out.PurpleBoxes == nil {
					if !in.IsDelim(']') {
						out.PurpleBoxes = make([]TargetBox, 0, 2)
					} else {
						out.PurpleBoxes = []TargetBox{}
					}
				} else {
					out.PurpleBoxes = (out.PurpleBoxes)[:0]
				}
				for !in.IsDelim(']') {
					var v2 TargetBox
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.PurpleBoxes = append(out.PurpleBoxes, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "confidence_score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfidenceScore = float64(in.Float64())
			}
		case "degree":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Degree = string(in.String())
			}
		case "sub_structures":
			if in.IsNull() {
				in.Skip()
				out.SubStructures = nil
			} else {
				in.Delim('[')
				if out.SubStructures == nil {
					if !in.IsDelim(']') {
						out.SubStructures = make([]WaveStructure, 0, 0)
					} else {
						out.SubStructures = []WaveStructure{}
					}
				} else {
					out.SubStructures = (out.SubStructures)[:0]
				}
				for !in.IsDelim(']') {
					var v3 WaveStructure
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.SubStructures = append(out.SubStructures, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeWaveSightPkgModel(out *jwriter.Writer, in WaveStructure) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"pivots\":"
		out.RawString(prefix)
		if in.Pivots == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Pivots {
				if v4 > 0 {
					out.RawByte(',')
				}
				(v5).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.PurpleBoxes) != 0 {
		const prefix string = ",\"purple_boxes\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v6, v7 := range in.PurpleBoxes {
				if v6 > 0 {
					out.RawByte(',')
				}
				(v7).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"confidence_score\":"
		out.RawString(prefix)
		out.Float64(float64(in.ConfidenceScore))
	}
	if in.Degree != "" {
		const prefix string = ",\"degree\":"
		out.RawString(prefix)
		out.String(string(in.Degree))
	}
	if len(in.SubStructures) != 0 {
		const prefix string = ",\"sub_structures\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.SubStructures {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WaveStructure) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeWaveSightPkgModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WaveStructure) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeWaveSightPkgModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WaveStructure) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeWaveSightPkgModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WaveStructure) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeWaveSightPkgModel(l, v)
}
func easyjsonC80ae7adDecodeWaveSightPkgModel1(in *jlexer.Lexer, out *TargetBox) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "min_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinPrice = float64(in.Float64())
			}
		case "max_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxPrice = float64(in.Float64())
			}
		case "start_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartTime = int64(in.Int64())
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndTime = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeWaveSightPkgModel1(out *jwriter.Writer, in TargetBox) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"min_price\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.MinPrice))
	}
	{
		const prefix string = ",\"max_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.MaxPrice))
	}
	{
		const prefix string = ",\"start_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.StartTime))
	}
	{
		const prefix string = ",\"end_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.EndTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TargetBox) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeWaveSightPkgModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TargetBox) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeWaveSightPkgModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TargetBox) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeWaveSightPkgModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TargetBox) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeWaveSightPkgModel1(l, v)
}
func easyjsonC80ae7adDecodeWaveSightPkgModel2(in *jlexer.Lexer, out *ScenarioPair) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "primary":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Primary).UnmarshalEasyJSON(in)
			}
		case "alternate":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Alternate).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeWaveSightPkgModel2(out *jwriter.Writer, in ScenarioPair) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"primary\":"
		out.RawString(prefix[1:])
		(in.Primary).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"alternate\":"
		out.RawString(prefix)
		(in.Alternate).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScenarioPair) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeWaveSightPkgModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScenarioPair) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeWaveSightPkgModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScenarioPair) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeWaveSightPkgModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScenarioPair) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeWaveSightPkgModel2(l, v)
}
func easyjsonC80ae7adDecodeWaveSightPkgModel3(in *jlexer.Lexer, out *Pivot) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = PivotType(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeWaveSightPkgModel3(out *jwriter.Writer, in Pivot) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Pivot) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeWaveSightPkgModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Pivot) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeWaveSightPkgModel3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Pivot) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeWaveSightPkgModel3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Pivot) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeWaveSightPkgModel3(l, v)
}
func easyjsonC80ae7adDecodeWaveSightPkgModel4(in *jlexer.Lexer, out *MotiveWave) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start":
			if in.IsNull() {
				in.Skip()
				out.Start = nil
			} else {
				if out.Start == nil {
					out.Start = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Start).UnmarshalEasyJSON(in)
				}
			}
		case "w1":
			if in.IsNull() {
				in.Skip()
				out.W1 = nil
			} else {
				if out.W1 == nil {
					out.W1 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W1).UnmarshalEasyJSON(in)
				}
			}
		case "w2":
			if in.IsNull() {
				in.Skip()
				out.W2 = nil
			} else {
				if out.W2 == nil {
					out.W2 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W2).UnmarshalEasyJSON(in)
				}
			}
		case "w3":
			if in.IsNull() {
				in.Skip()
				out.W3 = nil
			} else {
				if out.W3 == nil {
					out.W3 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W3).UnmarshalEasyJSON(in)
				}
			}
		case "w4":
			if in.IsNull() {
				in.Skip()
				out.W4 = nil
			} else {
				if out.W4 == nil {
					out.W4 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W4).UnmarshalEasyJSON(in)
				}
			}
		case "w5":
			if in.IsNull() {
				in.Skip()
				out.W5 = nil
			} else {
				if out.W5 == nil {
					out.W5 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W5).UnmarshalEasyJSON(in)
				}
			}
		case "direction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Direction = string(in.String())
			}
		case "confidence_score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfidenceScore = float64(in.Float64())
			}
		case "purple_boxes":
			if in.IsNull() {
				in.Skip()
				out.PurpleBoxes = nil
			} else {
				in.Delim('[')
				if out.PurpleBoxes == nil {
					if !in.IsDelim(']') {
						out.PurpleBoxes = make([]TargetBox, 0, 2)
					} else {
						out.PurpleBoxes = []TargetBox{}
					}
				} else {
					out.PurpleBoxes = (out.PurpleBoxes)[:0]
				}
				for !in.IsDelim(']') {
					var v10 TargetBox
					if in.IsNull() {
						in.Skip()
					} else {
						(v10).UnmarshalEasyJSON(in)
					}
					out.PurpleBoxes = append(out.PurpleBoxes, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "is_diagonal":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsDiagonal = bool(in.Bool())
			}
		case "is_truncated":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsTruncated = bool(in.Bool())
			}
		case "degree":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Degree = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeWaveSightPkgModel4(out *jwriter.Writer, in MotiveWave) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start\":"
		out.RawString(prefix[1:])
		if in.Start == nil {
			out.RawString("null")
		} else {
			(*in.Start).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w1\":"
		out.RawString(prefix)
		if in.W1 == nil {
			out.RawString("null")
		} else {
			(*in.W1).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w2\":"
		out.RawString(prefix)
		if in.W2 == nil {
			out.RawString("null")
		} else {
			(*in.W2).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w3\":"
		out.RawString(prefix)
		if in.W3 == nil {
			out.RawString("null")
		} else {
			(*in.W3).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w4\":"
		out.RawString(prefix)
		if in.W4 == nil {
			out.RawString("null")
		} else {
			(*in.W4).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w5\":"
		out.RawString(prefix)
		if in.W5 == nil {
			out.RawString("null")
		} else {
			(*in.W5).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"direction\":"
		out.RawString(prefix)
		out.String(string(in.Direction))
	}
	{
		const prefix string = ",\"confidence_score\":"
		out.RawString(prefix)
		out.Float64(float64(in.ConfidenceScore))
	}
	if len(in.PurpleBoxes) != 0 {
		const prefix string = ",\"purple_boxes\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v11, v12 := range in.PurpleBoxes {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"is_diagonal\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDiagonal))
	}
	{
		const prefix string = ",\"is_truncated\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsTruncated))
	}
	if in.Degree != "" {
		const prefix string = ",\"degree\":"
		out.RawString(prefix)
		out.String(string(in.Degree))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MotiveWave) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeWaveSightPkgModel4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MotiveWave) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeWaveSightPkgModel4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MotiveWave) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeWaveSightPkgModel4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MotiveWave) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeWaveSightPkgModel4(l, v)
}
func easyjsonC80ae7adDecodeWaveSightPkgModel5(in *jlexer.Lexer, out *IncompleteWave) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start":
			if in.IsNull() {
				in.Skip()
				out.Start = nil
			} else {
				if out.Start == nil {
					out.Start = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Start).UnmarshalEasyJSON(in)
				}
			}
		case "w1":
			if in.IsNull() {
				in.Skip()
				out.W1 = nil
			} else {
				if out.W1 == nil {
					out.W1 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W1).UnmarshalEasyJSON(in)
				}
			}
		case "w2":
			if in.IsNull() {
				in.Skip()
				out.W2 = nil
			} else {
				if out.W2 == nil {
					out.W2 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W2).UnmarshalEasyJSON(in)
				}
			}
		case "w3":
			if in.IsNull() {
				in.Skip()
				out.W3 = nil
			} else {
				if out.W3 == nil {
					out.W3 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W3).UnmarshalEasyJSON(in)
				}
			}
		case "direction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Direction = string(in.String())
			}
		case "confidence_score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfidenceScore = float64(in.Float64())
			}
		case "target_box":
			if in.IsNull() {
				in.Skip()
				out.TargetBox = nil
			} else {
				if out.TargetBox == nil {
					out.TargetBox = new(TargetBox)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.TargetBox).UnmarshalEasyJSON(in)
				}
			}
		case "degree":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Degree = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeWaveSightPkgModel5(out *jwriter.Writer, in IncompleteWave) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start\":"
		out.RawString(prefix[1:])
		if in.Start == nil {
			out.RawString("null")
		} else {
			(*in.Start).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w1\":"
		out.RawString(prefix)
		if in.W1 == nil {
			out.RawString("null")
		} else {
			(*in.W1).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w2\":"
		out.RawString(prefix)
		if in.W2 == nil {
			out.RawString("null")
		} else {
			(*in.W2).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w3\":"
		out.RawString(prefix)
		if in.W3 == nil {
			out.RawString("null")
		} else {
			(*in.W3).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"direction\":"
		out.RawString(prefix)
		out.String(string(in.Direction))
	}
	{
		const prefix string = ",\"confidence_score\":"
		out.RawString(prefix)
		out.Float64(float64(in.ConfidenceScore))
	}
	if in.TargetBox != nil {
		const prefix string = ",\"target_box\":"
		out.RawString(prefix)
		(*in.TargetBox).MarshalEasyJSON(out)
	}
	if in.Degree != "" {
		const prefix string = ",\"degree\":"
		out.RawString(prefix)
		out.String(string(in.Degree))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IncompleteWave) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeWaveSightPkgModel5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IncompleteWave) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeWaveSightPkgModel5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IncompleteWave) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeWaveSightPkgModel5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IncompleteWave) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeWaveSightPkgModel5(l, v)
}
func easyjsonC80ae7adDecodeWaveSightPkgModel6(in *jlexer.Lexer, out *CorrectiveWave) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start":
			if in.IsNull() {
				in.Skip()
				out.Start = nil
			} else {
				if out.Start == nil {
					out.Start = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Start).UnmarshalEasyJSON(in)
				}
			}
		case "wa":
			if in.IsNull() {
				in.Skip()
				out.WA = nil
			} else {
				if out.WA == nil {
					out.WA = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WA).UnmarshalEasyJSON(in)
				}
			}
		case "wb":
			if in.IsNull() {
				in.Skip()
				out.WB = nil
			} else {
				if out.WB == nil {
					out.WB = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WB).UnmarshalEasyJSON(in)
				}
			}
		case "wc":
			if in.IsNull() {
				in.Skip()
				out.WC = nil
			} else {
				if out.WC == nil {
					out.WC = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WC).UnmarshalEasyJSON(in)
				}
			}
		case "wd":
			if in.IsNull() {
				in.Skip()
				out.WD = nil
			} else {
				if out.WD == nil {
					out.WD = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WD).UnmarshalEasyJSON(in)
				}
			}
		case "we":
			if in.IsNull() {
				in.Skip()
				out.WE = nil
			} else {
				if out.WE == nil {
					out.WE = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WE).UnmarshalEasyJSON(in)
				}
			}
		case "wx":
			if in.IsNull() {
				in.Skip()
				out.WX = nil
			} else {
				if out.WX == nil {
					out.WX = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.WX).UnmarshalEasyJSON(in)
				}
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "direction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Direction = string(in.String())
			}
		case "purple_boxes":
			if in.IsNull() {
				in.Skip()
				out.PurpleBoxes = nil
			} else {
				in.Delim('[')
				if out.PurpleBoxes == nil {
					if !in.IsDelim(']') {
						out.PurpleBoxes = make([]TargetBox, 0, 2)
					} else {
						out.PurpleBoxes = []TargetBox{}
					}
				} else {
					out.PurpleBoxes = (out.PurpleBoxes)[:0]
				}
				for !in.IsDelim(']') {
					var v13 TargetBox
					if in.IsNull() {
						in.Skip()
					} else {
						(v13).UnmarshalEasyJSON(in)
					}
					out.PurpleBoxes = append(out.PurpleBoxes, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "degree":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Degree = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeWaveSightPkgModel6(out *jwriter.Writer, in CorrectiveWave) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start\":"
		out.RawString(prefix[1:])
		if in.Start == nil {
			out.RawString("null")
		} else {
			(*in.Start).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"wa\":"
		out.RawString(prefix)
		if in.WA == nil {
			out.RawString("null")
		} else {
			(*in.WA).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"wb\":"
		out.RawString(prefix)
		if in.WB == nil {
			out.RawString("null")
		} else {
			(*in.WB).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"wc\":"
		out.RawString(prefix)
		if in.WC == nil {
			out.RawString("null")
		} else {
			(*in.WC).MarshalEasyJSON(out)
		}
	}
	if in.WD != nil {
		const prefix string = ",\"wd\":"
		out.RawString(prefix)
		(*in.WD).MarshalEasyJSON(out)
	}
	if in.WE != nil {
		const prefix string = ",\"we\":"
		out.RawString(prefix)
		(*in.WE).MarshalEasyJSON(out)
	}
	if in.WX != nil {
		const prefix string = ",\"wx\":"
		out.RawString(prefix)
		(*in.WX).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"direction\":"
		out.RawString(prefix)
		out.String(string(in.Direction))
	}
	if len(in.PurpleBoxes) != 0 {
		const prefix string = ",\"purple_boxes\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v14, v15 := range in.PurpleBoxes {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Degree != "" {
		const prefix string = ",\"degree\":"
		out.RawString(prefix)
		out.String(string(in.Degree))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CorrectiveWave) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeWaveSightPkgModel6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CorrectiveWave) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeWaveSightPkgModel6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CorrectiveWave) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeWaveSightPkgModel6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CorrectiveWave) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeWaveSightPkgModel6(l, v)
}
func easyjsonC80ae7adDecodeWaveSightPkgModel7(in *jlexer.Lexer, out *Candle) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "open":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Open = float64(in.Float64())
			}
		case "high":
			if in.IsNull() {
				in.Skip()
			} else {
				out.High = float64(in.Float64())
			}
		case "low":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Low = float64(in.Float64())
			}
		case "close":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Close = float64(in.Float64())
			}
		case "volume":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Volume = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeWaveSightPkgModel7(out *jwriter.Writer, in Candle) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"open\":"
		out.RawString(prefix)
		out.Float64(float64(in.Open))
	}
	{
		const prefix string = ",\"high\":"
		out.RawString(prefix)
		out.Float64(float64(in.High))
	}
	{
		const prefix string = ",\"low\":"
		out.RawString(prefix)
		out.Float64(float64(in.Low))
	}
	{
		const prefix string = ",\"close\":"
		out.RawString(prefix)
		out.Float64(float64(in.Close))
	}
	{
		const prefix string = ",\"volume\":"
		out.RawString(prefix)
		out.Float64(float64(in.Volume))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Candle) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeWaveSightPkgModel7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Candle) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeWaveSightPkgModel7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Candle) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeWaveSightPkgModel7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Candle) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeWaveSightPkgModel7(l, v)
}
func easyjsonC80ae7adDecodeWaveSightPkgModel8(in *jlexer.Lexer, out *AnalysisScenario) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "bias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bias = string(in.String())
			}
		case "confidence":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confidence = float64(in.Float64())
			}
		case "structures":
			if in.IsNull() {
				in.Skip()
				out.Structures = nil
			} else {
				in.Delim('[')
				if out.Structures == nil {
					if !in.IsDelim(']') {
						out.Structures = make([]WaveStructure, 0, 0)
					} else {
						out.Structures = []WaveStructure{}
					}
				} else {
					out.Structures = (out.Structures)[:0]
				}
				for !in.IsDelim(']') {
					var v16 WaveStructure
					if in.IsNull() {
						in.Skip()
					} else {
						(v16).UnmarshalEasyJSON(in)
					}
					out.Structures = append(out.Structures, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeWaveSightPkgModel8(out *jwriter.Writer, in AnalysisScenario) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bias\":"
		out.RawString(prefix[1:])
		out.String(string(in.Bias))
	}
	{
		const prefix string = ",\"confidence\":"
		out.RawString(prefix)
		out.Float64(float64(in.Confidence))
	}
	{
		const prefix string = ",\"structures\":"
		out.RawString(prefix)
		if in.Structures == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.Structures {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalysisScenario) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeWaveSightPkgModel8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalysisScenario) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeWaveSightPkgModel8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalysisScenario) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeWaveSightPkgModel8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalysisScenario) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeWaveSightPkgModel8(l, v)
}
func easyjsonC80ae7adDecodeWaveSightPkgModel9(in *jlexer.Lexer, out *AnalysisResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ticker":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Ticker = string(in.String())
			}
		case "timeframe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timeframe = string(in.String())
			}
		case "candles":
			if in.IsNull() {
				in.Skip()
				out.Candles = nil
			} else {
				in.Delim('[')
				if out.Candles == nil {
					if !in.IsDelim(']') {
						out.Candles = make([]Candle, 0, 1)
					} else {
						out.Candles = []Candle{}
					}
				} else {
					out.Candles = (out.Candles)[:0]
				}
				for !in.IsDelim(']') {
					var v19 Candle
					if in.IsNull() {
						in.Skip()
					} else {
						(v19).UnmarshalEasyJSON(in)
					}
					out.Candles = append(out.Candles, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "scenarios":
			if in.IsNull() {
				in.Skip()
				out.Scenarios = nil
			} else {
				if out.Scenarios == nil {
					out.Scenarios = new(ScenarioPair)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Scenarios).UnmarshalEasyJSON(in)
				}
			}
		case "motive_waves":
			if in.IsNull() {
				in.Skip()
				out.MotiveWaves = nil
			} else {
				in.Delim('[')
				if out.MotiveWaves == nil {
					if !in.IsDelim(']') {
						out.MotiveWaves = make([]MotiveWave, 0, 0)
					} else {
						out.MotiveWaves = []MotiveWave{}
					}
				} else {
					out.MotiveWaves = (out.MotiveWaves)[:0]
				}
				for !in.IsDelim(']') {
					var v20 MotiveWave
					if in.IsNull() {
						in.Skip()
					} else {
						(v20).UnmarshalEasyJSON(in)
					}
					out.MotiveWaves = append(out.MotiveWaves, v20)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "corrective_waves":
			if in.IsNull() {
				in.Skip()
				out.CorrectiveWaves = nil
			} else {
				in.Delim('[')
				if out.CorrectiveWaves == nil {
					if !in.IsDelim(']') {
						out.CorrectiveWaves = make([]CorrectiveWave, 0, 0)
					} else {
						out.CorrectiveWaves = []CorrectiveWave{}
					}
				} else {
					out.CorrectiveWaves = (out.CorrectiveWaves)[:0]
				}
				for !in.IsDelim(']') {
					var v21 CorrectiveWave
					if in.IsNull() {
						in.Skip()
					} else {
						(v21).UnmarshalEasyJSON(in)
					}
					out.CorrectiveWaves = append(out.CorrectiveWaves, v21)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "incomplete_waves":
			if in.IsNull() {
				in.Skip()
				out.IncompleteWaves = nil
			} else {
				in.Delim('[')
				if out.IncompleteWaves == nil {
					if !in.IsDelim(']') {
						out.IncompleteWaves = make([]IncompleteWave, 0, 0)
					} else {
						out.IncompleteWaves = []IncompleteWave{}
					}
				} else {
					out.IncompleteWaves = (out.IncompleteWaves)[:0]
				}
				for !in.IsDelim(']') {
					var v22 IncompleteWave
					if in.IsNull() {
						in.Skip()
					} else {
						(v22).UnmarshalEasyJSON(in)
					}
					out.IncompleteWaves = append(out.IncompleteWaves, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeWaveSightPkgModel9(out *jwriter.Writer, in AnalysisResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ticker\":"
		out.RawString(prefix[1:])
		out.String(string(in.Ticker))
	}
	{
		const prefix string = ",\"timeframe\":"
		out.RawString(prefix)
		out.String(string(in.Timeframe))
	}
	{
		const prefix string = ",\"candles\":"
		out.RawString(prefix)
		if in.Candles == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.Candles {
				if v23 > 0 {
					out.RawByte(',')
				}
				(v24).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Scenarios != nil {
		const prefix string = ",\"scenarios\":"
		out.RawString(prefix)
		(*in.Scenarios).MarshalEasyJSON(out)
	}
	if len(in.MotiveWaves) != 0 {
		const prefix string = ",\"motive_waves\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v25, v26 := range in.MotiveWaves {
				if v25 > 0 {
					out.RawByte(',')
				}
				(v26).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.CorrectiveWaves) != 0 {
		const prefix string = ",\"corrective_waves\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v27, v28 := range in.CorrectiveWaves {
				if v27 > 0 {
					out.RawByte(',')
				}
				(v28).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.IncompleteWaves) != 0 {
		const prefix string = ",\"incomplete_waves\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v29, v30 := range in.IncompleteWaves {
				if v29 > 0 {
					out.RawByte(',')
				}
				(v30).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalysisResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeWaveSightPkgModel9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalysisResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeWaveSightPkgModel9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalysisResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeWaveSightPkgModel9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalysisResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeWaveSightPkgModel9(l, v)
}
