// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson60d273c4DecodeWaveSightPkgModel(in *jlexer.Lexer, out *MotiveWave) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start":
			if in.IsNull() {
				in.Skip()
				out.Start = nil
			} else {
				if out.Start == nil {
					out.Start = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Start).UnmarshalEasyJSON(in)
				}
			}
		case "w1":
			if in.IsNull() {
				in.Skip()
				out.W1 = nil
			} else {
				if out.W1 == nil {
					out.W1 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W1).UnmarshalEasyJSON(in)
				}
			}
		case "w2":
			if in.IsNull() {
				in.Skip()
				out.W2 = nil
			} else {
				if out.W2 == nil {
					out.W2 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W2).UnmarshalEasyJSON(in)
				}
			}
		case "w3":
			if in.IsNull() {
				in.Skip()
				out.W3 = nil
			} else {
				if out.W3 == nil {
					out.W3 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W3).UnmarshalEasyJSON(in)
				}
			}
		case "w4":
			if in.IsNull() {
				in.Skip()
				out.W4 = nil
			} else {
				if out.W4 == nil {
					out.W4 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W4).UnmarshalEasyJSON(in)
				}
			}
		case "w5":
			if in.IsNull() {
				in.Skip()
				out.W5 = nil
			} else {
				if out.W5 == nil {
					out.W5 = new(Pivot)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.W5).UnmarshalEasyJSON(in)
				}
			}
		case "direction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Direction = string(in.String())
			}
		case "confidence_score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfidenceScore = float64(in.Float64())
			}
		case "purple_boxes":
			if in.IsNull() {
				in.Skip()
				out.PurpleBoxes = nil
			} else {
				in.Delim('[')
				if out.PurpleBoxes == nil {
					if !in.IsDelim(']') {
						out.PurpleBoxes = make([]TargetBox, 0, 2)
					} else {
						out.PurpleBoxes = []TargetBox{}
					}
				} else {
					out.PurpleBoxes = (out.PurpleBoxes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 TargetBox
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.PurpleBoxes = append(out.PurpleBoxes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "is_diagonal":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsDiagonal = bool(in.Bool())
			}
		case "is_truncated":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsTruncated = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson60d273c4EncodeWaveSightPkgModel(out *jwriter.Writer, in MotiveWave) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start\":"
		out.RawString(prefix[1:])
		if in.Start == nil {
			out.RawString("null")
		} else {
			(*in.Start).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w1\":"
		out.RawString(prefix)
		if in.W1 == nil {
			out.RawString("null")
		} else {
			(*in.W1).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w2\":"
		out.RawString(prefix)
		if in.W2 == nil {
			out.RawString("null")
		} else {
			(*in.W2).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w3\":"
		out.RawString(prefix)
		if in.W3 == nil {
			out.RawString("null")
		} else {
			(*in.W3).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w4\":"
		out.RawString(prefix)
		if in.W4 == nil {
			out.RawString("null")
		} else {
			(*in.W4).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"w5\":"
		out.RawString(prefix)
		if in.W5 == nil {
			out.RawString("null")
		} else {
			(*in.W5).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"direction\":"
		out.RawString(prefix)
		out.String(string(in.Direction))
	}
	{
		const prefix string = ",\"confidence_score\":"
		out.RawString(prefix)
		out.Float64(float64(in.ConfidenceScore))
	}
	if len(in.PurpleBoxes) != 0 {
		const prefix string = ",\"purple_boxes\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v2, v3 := range in.PurpleBoxes {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"is_diagonal\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDiagonal))
	}
	{
		const prefix string = ",\"is_truncated\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsTruncated))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MotiveWave) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson60d273c4EncodeWaveSightPkgModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MotiveWave) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson60d273c4EncodeWaveSightPkgModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MotiveWave) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson60d273c4DecodeWaveSightPkgModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MotiveWave) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson60d273c4DecodeWaveSightPkgModel(l, v)
}
