// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson60d273c4DecodeWaveSightPkgModel(in *jlexer.Lexer, out *MotiveWave) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "start":
			if in.IsNull() {
				in.Skip()
				out.Start = nil
			} else {
				if out.Start == nil {
					out.Start = new(Pivot)
				}
				easyjson60d273c4DecodeWaveSightPkgModel1(in, out.Start)
			}
		case "w1":
			if in.IsNull() {
				in.Skip()
				out.W1 = nil
			} else {
				if out.W1 == nil {
					out.W1 = new(Pivot)
				}
				easyjson60d273c4DecodeWaveSightPkgModel1(in, out.W1)
			}
		case "w2":
			if in.IsNull() {
				in.Skip()
				out.W2 = nil
			} else {
				if out.W2 == nil {
					out.W2 = new(Pivot)
				}
				easyjson60d273c4DecodeWaveSightPkgModel1(in, out.W2)
			}
		case "w3":
			if in.IsNull() {
				in.Skip()
				out.W3 = nil
			} else {
				if out.W3 == nil {
					out.W3 = new(Pivot)
				}
				easyjson60d273c4DecodeWaveSightPkgModel1(in, out.W3)
			}
		case "w4":
			if in.IsNull() {
				in.Skip()
				out.W4 = nil
			} else {
				if out.W4 == nil {
					out.W4 = new(Pivot)
				}
				easyjson60d273c4DecodeWaveSightPkgModel1(in, out.W4)
			}
		case "w5":
			if in.IsNull() {
				in.Skip()
				out.W5 = nil
			} else {
				if out.W5 == nil {
					out.W5 = new(Pivot)
				}
				easyjson60d273c4DecodeWaveSightPkgModel1(in, out.W5)
			}
		case "direction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Direction = string(in.String())
			}
		case "confidence_score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfidenceScore = float64(in.Float64())
			}
		case "purple_box":
			if in.IsNull() {
				in.Skip()
				out.PurpleBox = nil
			} else {
				if out.PurpleBox == nil {
					out.PurpleBox = new(TargetBox)
				}
				easyjson60d273c4DecodeWaveSightPkgModel2(in, out.PurpleBox)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson60d273c4EncodeWaveSightPkgModel(out *jwriter.Writer, in MotiveWave) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start\":"
		out.RawString(prefix[1:])
		if in.Start == nil {
			out.RawString("null")
		} else {
			easyjson60d273c4EncodeWaveSightPkgModel1(out, *in.Start)
		}
	}
	{
		const prefix string = ",\"w1\":"
		out.RawString(prefix)
		if in.W1 == nil {
			out.RawString("null")
		} else {
			easyjson60d273c4EncodeWaveSightPkgModel1(out, *in.W1)
		}
	}
	{
		const prefix string = ",\"w2\":"
		out.RawString(prefix)
		if in.W2 == nil {
			out.RawString("null")
		} else {
			easyjson60d273c4EncodeWaveSightPkgModel1(out, *in.W2)
		}
	}
	{
		const prefix string = ",\"w3\":"
		out.RawString(prefix)
		if in.W3 == nil {
			out.RawString("null")
		} else {
			easyjson60d273c4EncodeWaveSightPkgModel1(out, *in.W3)
		}
	}
	{
		const prefix string = ",\"w4\":"
		out.RawString(prefix)
		if in.W4 == nil {
			out.RawString("null")
		} else {
			easyjson60d273c4EncodeWaveSightPkgModel1(out, *in.W4)
		}
	}
	{
		const prefix string = ",\"w5\":"
		out.RawString(prefix)
		if in.W5 == nil {
			out.RawString("null")
		} else {
			easyjson60d273c4EncodeWaveSightPkgModel1(out, *in.W5)
		}
	}
	{
		const prefix string = ",\"direction\":"
		out.RawString(prefix)
		out.String(string(in.Direction))
	}
	{
		const prefix string = ",\"confidence_score\":"
		out.RawString(prefix)
		out.Float64(float64(in.ConfidenceScore))
	}
	if in.PurpleBox != nil {
		const prefix string = ",\"purple_box\":"
		out.RawString(prefix)
		easyjson60d273c4EncodeWaveSightPkgModel2(out, *in.PurpleBox)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MotiveWave) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson60d273c4EncodeWaveSightPkgModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MotiveWave) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson60d273c4EncodeWaveSightPkgModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MotiveWave) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson60d273c4DecodeWaveSightPkgModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MotiveWave) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson60d273c4DecodeWaveSightPkgModel(l, v)
}
func easyjson60d273c4DecodeWaveSightPkgModel2(in *jlexer.Lexer, out *TargetBox) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "min_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinPrice = float64(in.Float64())
			}
		case "max_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxPrice = float64(in.Float64())
			}
		case "start_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartTime = int64(in.Int64())
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndTime = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson60d273c4EncodeWaveSightPkgModel2(out *jwriter.Writer, in TargetBox) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"min_price\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.MinPrice))
	}
	{
		const prefix string = ",\"max_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.MaxPrice))
	}
	{
		const prefix string = ",\"start_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.StartTime))
	}
	{
		const prefix string = ",\"end_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.EndTime))
	}
	out.RawByte('}')
}
func easyjson60d273c4DecodeWaveSightPkgModel1(in *jlexer.Lexer, out *Pivot) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = PivotType(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson60d273c4EncodeWaveSightPkgModel1(out *jwriter.Writer, in Pivot) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	out.RawByte('}')
}
