// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6ff3ac1dDecodeWaveSightPkgModel(in *jlexer.Lexer, out *WaveStructure) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "pivots":
			if in.IsNull() {
				in.Skip()
				out.Pivots = nil
			} else {
				in.Delim('[')
				if out.Pivots == nil {
					if !in.IsDelim(']') {
						out.Pivots = make([]Pivot, 0, 2)
					} else {
						out.Pivots = []Pivot{}
					}
				} else {
					out.Pivots = (out.Pivots)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Pivot
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Pivots = append(out.Pivots, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "purple_boxes":
			if in.IsNull() {
				in.Skip()
				out.PurpleBoxes = nil
			} else {
				in.Delim('[')
				if out.PurpleBoxes == nil {
					if !in.IsDelim(']') {
						out.PurpleBoxes = make([]TargetBox, 0, 2)
					} else {
						out.PurpleBoxes = []TargetBox{}
					}
				} else {
					out.PurpleBoxes = (out.PurpleBoxes)[:0]
				}
				for !in.IsDelim(']') {
					var v2 TargetBox
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.PurpleBoxes = append(out.PurpleBoxes, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "confidence_score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfidenceScore = float64(in.Float64())
			}
		case "degree":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Degree = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeWaveSightPkgModel(out *jwriter.Writer, in WaveStructure) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"pivots\":"
		out.RawString(prefix)
		if in.Pivots == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Pivots {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.PurpleBoxes) != 0 {
		const prefix string = ",\"purple_boxes\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v5, v6 := range in.PurpleBoxes {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"confidence_score\":"
		out.RawString(prefix)
		out.Float64(float64(in.ConfidenceScore))
	}
	if in.Degree != "" {
		const prefix string = ",\"degree\":"
		out.RawString(prefix)
		out.String(string(in.Degree))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WaveStructure) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeWaveSightPkgModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WaveStructure) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeWaveSightPkgModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WaveStructure) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeWaveSightPkgModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WaveStructure) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeWaveSightPkgModel(l, v)
}
func easyjson6ff3ac1dDecodeWaveSightPkgModel1(in *jlexer.Lexer, out *ScenarioPair) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "primary":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Primary).UnmarshalEasyJSON(in)
			}
		case "alternate":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Alternate).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeWaveSightPkgModel1(out *jwriter.Writer, in ScenarioPair) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"primary\":"
		out.RawString(prefix[1:])
		(in.Primary).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"alternate\":"
		out.RawString(prefix)
		(in.Alternate).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScenarioPair) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeWaveSightPkgModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScenarioPair) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeWaveSightPkgModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScenarioPair) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeWaveSightPkgModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScenarioPair) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeWaveSightPkgModel1(l, v)
}
func easyjson6ff3ac1dDecodeWaveSightPkgModel2(in *jlexer.Lexer, out *AnalysisScenario) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "bias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bias = string(in.String())
			}
		case "confidence":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confidence = float64(in.Float64())
			}
		case "structures":
			if in.IsNull() {
				in.Skip()
				out.Structures = nil
			} else {
				in.Delim('[')
				if out.Structures == nil {
					if !in.IsDelim(']') {
						out.Structures = make([]WaveStructure, 0, 0)
					} else {
						out.Structures = []WaveStructure{}
					}
				} else {
					out.Structures = (out.Structures)[:0]
				}
				for !in.IsDelim(']') {
					var v7 WaveStructure
					if in.IsNull() {
						in.Skip()
					} else {
						(v7).UnmarshalEasyJSON(in)
					}
					out.Structures = append(out.Structures, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeWaveSightPkgModel2(out *jwriter.Writer, in AnalysisScenario) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bias\":"
		out.RawString(prefix[1:])
		out.String(string(in.Bias))
	}
	{
		const prefix string = ",\"confidence\":"
		out.RawString(prefix)
		out.Float64(float64(in.Confidence))
	}
	{
		const prefix string = ",\"structures\":"
		out.RawString(prefix)
		if in.Structures == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Structures {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalysisScenario) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeWaveSightPkgModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalysisScenario) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeWaveSightPkgModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalysisScenario) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeWaveSightPkgModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalysisScenario) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeWaveSightPkgModel2(l, v)
}
func easyjson6ff3ac1dDecodeWaveSightPkgModel3(in *jlexer.Lexer, out *AnalysisResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ticker":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Ticker = string(in.String())
			}
		case "timeframe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timeframe = string(in.String())
			}
		case "candles":
			if in.IsNull() {
				in.Skip()
				out.Candles = nil
			} else {
				in.Delim('[')
				if out.Candles == nil {
					if !in.IsDelim(']') {
						out.Candles = make([]Candle, 0, 1)
					} else {
						out.Candles = []Candle{}
					}
				} else {
					out.Candles = (out.Candles)[:0]
				}
				for !in.IsDelim(']') {
					var v10 Candle
					if in.IsNull() {
						in.Skip()
					} else {
						(v10).UnmarshalEasyJSON(in)
					}
					out.Candles = append(out.Candles, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "scenarios":
			if in.IsNull() {
				in.Skip()
				out.Scenarios = nil
			} else {
				if out.Scenarios == nil {
					out.Scenarios = new(ScenarioPair)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Scenarios).UnmarshalEasyJSON(in)
				}
			}
		case "motive_waves":
			if in.IsNull() {
				in.Skip()
				out.MotiveWaves = nil
			} else {
				in.Delim('[')
				if out.MotiveWaves == nil {
					if !in.IsDelim(']') {
						out.MotiveWaves = make([]MotiveWave, 0, 0)
					} else {
						out.MotiveWaves = []MotiveWave{}
					}
				} else {
					out.MotiveWaves = (out.MotiveWaves)[:0]
				}
				for !in.IsDelim(']') {
					var v11 MotiveWave
					if in.IsNull() {
						in.Skip()
					} else {
						(v11).UnmarshalEasyJSON(in)
					}
					out.MotiveWaves = append(out.MotiveWaves, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "corrective_waves":
			if in.IsNull() {
				in.Skip()
				out.CorrectiveWaves = nil
			} else {
				in.Delim('[')
				if out.CorrectiveWaves == nil {
					if !in.IsDelim(']') {
						out.CorrectiveWaves = make([]CorrectiveWave, 0, 0)
					} else {
						out.CorrectiveWaves = []CorrectiveWave{}
					}
				} else {
					out.CorrectiveWaves = (out.CorrectiveWaves)[:0]
				}
				for !in.IsDelim(']') {
					var v12 CorrectiveWave
					if in.IsNull() {
						in.Skip()
					} else {
						(v12).UnmarshalEasyJSON(in)
					}
					out.CorrectiveWaves = append(out.CorrectiveWaves, v12)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "incomplete_waves":
			if in.IsNull() {
				in.Skip()
				out.IncompleteWaves = nil
			} else {
				in.Delim('[')
				if out.IncompleteWaves == nil {
					if !in.IsDelim(']') {
						out.IncompleteWaves = make([]IncompleteWave, 0, 0)
					} else {
						out.IncompleteWaves = []IncompleteWave{}
					}
				} else {
					out.IncompleteWaves = (out.IncompleteWaves)[:0]
				}
				for !in.IsDelim(']') {
					var v13 IncompleteWave
					if in.IsNull() {
						in.Skip()
					} else {
						(v13).UnmarshalEasyJSON(in)
					}
					out.IncompleteWaves = append(out.IncompleteWaves, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeWaveSightPkgModel3(out *jwriter.Writer, in AnalysisResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ticker\":"
		out.RawString(prefix[1:])
		out.String(string(in.Ticker))
	}
	{
		const prefix string = ",\"timeframe\":"
		out.RawString(prefix)
		out.String(string(in.Timeframe))
	}
	{
		const prefix string = ",\"candles\":"
		out.RawString(prefix)
		if in.Candles == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Candles {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Scenarios != nil {
		const prefix string = ",\"scenarios\":"
		out.RawString(prefix)
		(*in.Scenarios).MarshalEasyJSON(out)
	}
	if len(in.MotiveWaves) != 0 {
		const prefix string = ",\"motive_waves\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v16, v17 := range in.MotiveWaves {
				if v16 > 0 {
					out.RawByte(',')
				}
				(v17).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.CorrectiveWaves) != 0 {
		const prefix string = ",\"corrective_waves\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v18, v19 := range in.CorrectiveWaves {
				if v18 > 0 {
					out.RawByte(',')
				}
				(v19).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.IncompleteWaves) != 0 {
		const prefix string = ",\"incomplete_waves\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v20, v21 := range in.IncompleteWaves {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalysisResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeWaveSightPkgModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalysisResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeWaveSightPkgModel3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalysisResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeWaveSightPkgModel3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalysisResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeWaveSightPkgModel3(l, v)
}
