// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6ff3ac1dDecodeWaveSightPkgModel(in *jlexer.Lexer, out *AnalysisResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ticker":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Ticker = string(in.String())
			}
		case "timeframe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timeframe = string(in.String())
			}
		case "candles":
			if in.IsNull() {
				in.Skip()
				out.Candles = nil
			} else {
				in.Delim('[')
				if out.Candles == nil {
					if !in.IsDelim(']') {
						out.Candles = make([]Candle, 0, 1)
					} else {
						out.Candles = []Candle{}
					}
				} else {
					out.Candles = (out.Candles)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Candle
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Candles = append(out.Candles, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "motive_waves":
			if in.IsNull() {
				in.Skip()
				out.MotiveWaves = nil
			} else {
				in.Delim('[')
				if out.MotiveWaves == nil {
					if !in.IsDelim(']') {
						out.MotiveWaves = make([]MotiveWave, 0, 0)
					} else {
						out.MotiveWaves = []MotiveWave{}
					}
				} else {
					out.MotiveWaves = (out.MotiveWaves)[:0]
				}
				for !in.IsDelim(']') {
					var v2 MotiveWave
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.MotiveWaves = append(out.MotiveWaves, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "corrective_waves":
			if in.IsNull() {
				in.Skip()
				out.CorrectiveWaves = nil
			} else {
				in.Delim('[')
				if out.CorrectiveWaves == nil {
					if !in.IsDelim(']') {
						out.CorrectiveWaves = make([]CorrectiveWave, 0, 1)
					} else {
						out.CorrectiveWaves = []CorrectiveWave{}
					}
				} else {
					out.CorrectiveWaves = (out.CorrectiveWaves)[:0]
				}
				for !in.IsDelim(']') {
					var v3 CorrectiveWave
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.CorrectiveWaves = append(out.CorrectiveWaves, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "incomplete_waves":
			if in.IsNull() {
				in.Skip()
				out.IncompleteWaves = nil
			} else {
				in.Delim('[')
				if out.IncompleteWaves == nil {
					if !in.IsDelim(']') {
						out.IncompleteWaves = make([]IncompleteWave, 0, 1)
					} else {
						out.IncompleteWaves = []IncompleteWave{}
					}
				} else {
					out.IncompleteWaves = (out.IncompleteWaves)[:0]
				}
				for !in.IsDelim(']') {
					var v4 IncompleteWave
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.IncompleteWaves = append(out.IncompleteWaves, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeWaveSightPkgModel(out *jwriter.Writer, in AnalysisResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ticker\":"
		out.RawString(prefix[1:])
		out.String(string(in.Ticker))
	}
	{
		const prefix string = ",\"timeframe\":"
		out.RawString(prefix)
		out.String(string(in.Timeframe))
	}
	{
		const prefix string = ",\"candles\":"
		out.RawString(prefix)
		if in.Candles == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Candles {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"motive_waves\":"
		out.RawString(prefix)
		if in.MotiveWaves == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.MotiveWaves {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"corrective_waves\":"
		out.RawString(prefix)
		if in.CorrectiveWaves == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.CorrectiveWaves {
				if v9 > 0 {
					out.RawByte(',')
				}
				(v10).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"incomplete_waves\":"
		out.RawString(prefix)
		if in.IncompleteWaves == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.IncompleteWaves {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalysisResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeWaveSightPkgModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalysisResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeWaveSightPkgModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalysisResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeWaveSightPkgModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalysisResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeWaveSightPkgModel(l, v)
}
