// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD0f11979DecodeWaveSightPkgModel(in *jlexer.Lexer, out *TargetBox) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "min_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinPrice = float64(in.Float64())
			}
		case "max_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxPrice = float64(in.Float64())
			}
		case "start_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartTime = int64(in.Int64())
			}
		case "end_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndTime = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD0f11979EncodeWaveSightPkgModel(out *jwriter.Writer, in TargetBox) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"min_price\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.MinPrice))
	}
	{
		const prefix string = ",\"max_price\":"
		out.RawString(prefix)
		out.Float64(float64(in.MaxPrice))
	}
	{
		const prefix string = ",\"start_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.StartTime))
	}
	{
		const prefix string = ",\"end_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.EndTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TargetBox) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD0f11979EncodeWaveSightPkgModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TargetBox) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD0f11979EncodeWaveSightPkgModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TargetBox) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD0f11979DecodeWaveSightPkgModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TargetBox) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD0f11979DecodeWaveSightPkgModel(l, v)
}
